/****************************** Ghost.github.io ******************************\
*	Module Name:	FrmHesabColCed.cs
*	Project:		EtelaatePaye
*	Copyright (C) 2018 Kamal Khayati, All rights reserved.
*	This software may be modified and distributed under the terms of the MIT license.  See LICENSE file for details.
*
*	Written by Kamal Khayati <Kamal1355@gmail.com>,  2019 / 2 / 9   06:10 ب.ظ
*	
***********************************************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace EtelaatePaye.CodingHesabdari
{
    public partial class FrmHesabColCed : DevExpress.XtraEditors.XtraForm
    {
        FrmHesabColList Fm;

        public FrmHesabColCed(FrmHesabColList fm)
        {
            InitializeComponent();
            Fm = fm;
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DBHesabdari_TG.MyContext dbContext = new DBHesabdari_TG.MyContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.EpHesabGroups.Load();
            // This line of code is generated by Data Source Configuration Wizard
            epHesabGroupsBindingSource.DataSource = dbContext.EpHesabGroups.Local.ToBindingList();
        }
    }
}