/****************************** Ghost.github.io ******************************\
*	Module Name:	FrmDoreMaliCed.cs
*	Project:		SystemManagement
*	Copyright (C) 2018 Kamal Khayati, All rights reserved.
*	This software may be modified and distributed under the terms of the MIT license.  See LICENSE file for details.
*
*	Written by Kamal Khayati <Kamal1355@gmail.com>,  2018 / 12 / 31   04:07 ب.ظ
*	
***********************************************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DBHesabdari_TG;
using HelpClassLibrary;
using System.Data.Entity;
using System.Globalization;

namespace SystemManagement.DafaterMali
{
    public partial class FrmDorehaCed : DevExpress.XtraEditors.XtraForm
    {
        FrmDorehaList Fm;
        public FrmDorehaCed(FrmDorehaList fm)
        {
            InitializeComponent();
            Fm = fm;
        }
        int _ShobeId = 0;
        public void FillcmbMajmoehaList()
        {
            //var db = new MyContext();
            //db.MsMajmoes.Where(s => s.IsActive == true).LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    msMajmoesBindingSource.DataSource = db.MsMajmoes.Local.ToBindingList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsMajmoes.Any())
                    {
                        // This line of code is generated by Data Source Configuration Wizard
                        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
                        db.MsMajmoes.Where(s => s.MajmoeIsActive == true).Load();
                        // Bind data to control when loading complete
                        msMajmoesBindingSource.DataSource = db.MsMajmoes.Local.ToBindingList();

                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
        public void FillcmbVahedhaList()
        {
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsVaheds.Any())
                    {
                        int _MajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                        // This line of code is generated by Data Source Configuration Wizard
                        db.MsVaheds.Where(s => s.VahedIsActive == true && s.MsMajmoeId == _MajmoeId).Load();
                        // Bind data to control when loading complete
                        msVahedsBindingSource.DataSource = db.MsVaheds.Local.ToBindingList();
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
        public void FillcmbShobehaList()
        {
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsVaheds.Any())
                    {
                        int _VahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                        // This line of code is generated by Data Source Configuration Wizard
                        db.MsShobes.Where(s => s.ShobeIsActive == true && s.MsVahedId == _VahedId).Load();
                        // Bind data to control when loading complete
                        msShobesBindingSource.DataSource = db.MsShobes.Local.ToBindingList();
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
        public void FilltxtShobeCode()
        {
            using (var db = new MyContext())
            {
                try
                {
                    if (msShobesBindingSource.DataSource != null)
                    {
                        var q = db.MsShobes.FirstOrDefault(s => s.MsShobeId == _ShobeId);
                        if (q != null)
                            txtShobeCode.Text = q.ShobeCode.ToString();

                        btnNewCode_Click(null, null);
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
        private void btnNewCode_Click(object sender, EventArgs e)
        {
            if (cmbShobeList.EditValue != null)
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        var q = db.MsDoreMalis.Where(s => s.MsShobeId == _ShobeId);
                        if (q.Any())
                        {
                            var MaximumCod = q.Max(p => p.DoreMaliCode);
                            txtCode.Text = (MaximumCod + 1).ToString().Substring(6);
                        }
                        else
                        {
                            txtCode.Text = "001";
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }

        }

        string CodeBeforeEdit = "";
        string NameBeforeEdit = "";
        int RowId = 0;
        private void FrmDorehaCed_Load(object sender, EventArgs e)
        {
            FillcmbMajmoehaList();
            if (this.Text != "ایجاد رکورد جدید")
            {
                cmbMajmoehaList.EditValue = Convert.ToInt32(Fm.gridView1.GetFocusedRowCellValue("MsMajmoeId").ToString());
                cmbVahedhaList.EditValue = Convert.ToInt32(Fm.gridView1.GetFocusedRowCellValue("MsVahedId").ToString());
                cmbShobeList.EditValue = Convert.ToInt32(Fm.gridView1.GetFocusedRowCellValue("MsShobeId").ToString());
                txtId.Text = Fm.gridView1.GetFocusedRowCellValue("MsDoreMaliId").ToString();
                txtCode.Text = Fm.gridView1.GetFocusedRowCellValue("DoreMaliCode").ToString().Substring(6);
                txtDoreMali.Text = Fm.gridView1.GetFocusedRowCellValue("DoreMali").ToString();
                txtStartDore.EditValue = Fm.gridView1.GetFocusedRowCellValue("StartDoreMali").ToString().Substring(0, 10);
                txtEndDore.EditValue = Fm.gridView1.GetFocusedRowCellValue("EndDoreMali").ToString().Substring(0, 10);
                chkIsActive.Checked = Convert.ToBoolean(Fm.gridView1.GetFocusedRowCellValue("DoreMaliIsActive"));
                chkDoreIsClose.Checked = Convert.ToBoolean(Fm.gridView1.GetFocusedRowCellValue("DoreIsClose"));
                txtMaliat.Text = Fm.gridView1.GetFocusedRowCellValue("Maliat").ToString();
                txtAvarez.Text = Fm.gridView1.GetFocusedRowCellValue("Avarez").ToString();

                txtDoreMali.ReadOnly = true;
                CodeBeforeEdit = txtCode.Text;
                NameBeforeEdit = txtDoreMali.Text;
                RowId = Convert.ToInt32(txtId.Text);

            }
            else
            {
                HelpClass1.SetCurrentYear(txtDoreMali);
                txtStartDore.Text = txtDoreMali.Text + "/" + "01/01";
                txtEndDore.Text = txtDoreMali.Text + "/" + "12/29";
            }
        }

        private void btnCreateNext_Click(object sender, EventArgs e)
        {
            btnCreateCloseClicked = false;
            btnCreateClose_Click(null, null);
            btnCreateCloseClicked = true;

        }

        bool btnCreateCloseClicked = true;
        private void btnCreateClose_Click(object sender, EventArgs e)
        {

            if (TextEditValidation())
            {
                btnCreateClose.Enabled = false;
                btnCreateNext.Enabled = false;
                if (this.Text == "ایجاد رکورد جدید")
                {
                    using (var db = new MyContext())
                    {
                        try
                        {
                            MsDoreMali obj = new MsDoreMali();
                            obj.DoreMaliCode = Convert.ToInt32(txtShobeCode.Text + txtCode.Text);
                            obj.DoreMali = Convert.ToInt32(txtDoreMali.Text);
                            obj.StartDoreMali = Convert.ToDateTime(txtStartDore.Text);
                            obj.EndDoreMali = Convert.ToDateTime(txtEndDore.Text);
                            obj.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                            obj.MajmoeName = cmbMajmoehaList.Text;
                            obj.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                            obj.VahedName = cmbVahedhaList.Text;
                            obj.MsShobeId = Convert.ToInt32(cmbShobeList.EditValue);
                            obj.ShobeName = cmbShobeList.Text;
                            obj.DoreMaliIsActive = chkIsActive.Checked;
                            obj.DoreIsClose = chkDoreIsClose.Checked;
                            obj.Maliat = Convert.ToSingle(txtMaliat.Text.Replace('/', '.') != "" ? txtMaliat.Text.Replace('/', '.') : "0");
                            obj.Avarez = Convert.ToSingle(txtAvarez.Text.Replace('/', '.') != "" ? txtAvarez.Text.Replace('/', '.') : "0");
                            db.MsDoreMalis.Add(obj);
                            db.SaveChanges();

                            Fm.btnDisplyActiveList_ItemClick(null, null);
                            XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                            Fm.gridView1.MoveLast();
                            if (btnCreateCloseClicked)
                                this.Close();
                            else
                            {
                                btnCreateClose.Enabled = true;
                                btnCreateNext.Enabled = true;
                                btnNewCode_Click(null, null);
                                txtDoreMali.Text = "";
                                txtStartDore.Text = "";
                                txtEndDore.Text = "";
                                chkDoreIsClose.Checked = false;
                                txtMaliat.Text = "";
                                txtAvarez.Text = "";
                                txtDoreMali.Focus();
                            }
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
                else if (this.Text == "ویرایش رکورد جاری")
                {
                    using (var db = new MyContext())
                    {
                        try
                        {
                            //string _m= txtMaliat.Text.ToString();
                            //string _a = txtMaliat.Text.ToString();
                            //float _M = (float)_m;
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q = db.MsDoreMalis.FirstOrDefault(p => p.MsDoreMaliId == RowId);
                            if (q != null)
                            {
                                q.DoreMaliCode = Convert.ToInt32(txtShobeCode.Text + txtCode.Text);
                                q.DoreMali = Convert.ToInt32(txtDoreMali.Text);
                                q.StartDoreMali = Convert.ToDateTime(txtStartDore.Text);
                                q.EndDoreMali = Convert.ToDateTime(txtEndDore.Text);
                                q.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                q.MajmoeName = cmbMajmoehaList.Text;
                                q.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                                q.VahedName = cmbVahedhaList.Text;
                                q.MsShobeId = Convert.ToInt32(cmbShobeList.EditValue);
                                q.ShobeName = cmbShobeList.Text;
                                q.DoreMaliIsActive = chkIsActive.Checked;
                                q.DoreIsClose = chkDoreIsClose.Checked;
                                q.Maliat = Convert.ToSingle(txtMaliat.Text.Replace('/', '.') != "" ? txtMaliat.Text.Replace('/', '.') : "0");
                                q.Avarez = Convert.ToSingle(txtAvarez.Text.Replace('/', '.') != "" ? txtAvarez.Text.Replace('/', '.') : "0");
                                /////////////////////////////////////////////////////////////////////////////////////
                                db.SaveChanges();

                                Fm.btnDisplyActiveList_ItemClick(null, null);
                                XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                this.Close();
                                Fm.gridView1.FocusedRowHandle = HelpClass1.EditRowIndex;
                            }
                            else
                                XtraMessageBox.Show("رکورد جاری در بانک اطلاعاتی موجود نیست", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
                else if (this.Text == "حذف رکورد جاری")
                {
                    int RowId = Convert.ToInt32(txtId.Text);
                    using (var db = new MyContext())
                    {
                        try
                        {
                            var q = db.MsDoreMalis.FirstOrDefault(p => p.MsDoreMaliId == RowId);
                            if (q != null)
                            {
                                //////////////////////////////////////////////////////////////////////////////////
                                db.MsDoreMalis.Remove(q);
                                if (XtraMessageBox.Show("در صورت وجود اطلاعات در سال مالی انتخابی کلیه اطلاعات سال مالی فوق از سیستم حذف خواهد شد و قابل برگشت نمی باشد", "پیغام", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) == DialogResult.Yes)
                                {
                                    db.SaveChanges();
                                    Fm.btnDisplyActiveList_ItemClick(null, null);
                                    XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                    this.Close();
                                    Fm.gridView1.FocusedRowHandle = HelpClass1.EditRowIndex - 1;
                                }
                            }
                            else
                                XtraMessageBox.Show("رکورد جاری در بانک اطلاعاتی موجود نیست", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
            }

        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();

        }

        private bool TextEditValidation()
        {
            ///////////////// اعتبار سنجی کد ////////////////////////////////////
            if (string.IsNullOrEmpty(txtCode.Text))
            {
                XtraMessageBox.Show("لطفا کد را وارد کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else if (Convert.ToInt32(txtCode.Text) == 0)
            {
                XtraMessageBox.Show("کد وارده باید عددی بزرگتر از صفر باشد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                if (this.Text == "ایجاد رکورد جدید")
                {
                    btnNewCode_Click(null, null);
                }
                else
                {
                    txtCode.Text = CodeBeforeEdit;
                }

                return false;
            }
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        int _code = Convert.ToInt32(txtShobeCode.Text + txtCode.Text);
                        if (this.Text == "ایجاد رکورد جدید")
                        {
                            if (db.MsDoreMalis.Any())
                            {
                                var q1 = db.MsDoreMalis.Where(p => p.DoreMaliCode == _code);
                                if (q1.Any())
                                {
                                    XtraMessageBox.Show("این کد قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                    btnNewCode_Click(null, null);
                                    return false;
                                }
                            }
                        }
                        else if (this.Text == "ویرایش رکورد جاری")
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q1 = db.MsDoreMalis.Where(p => p.MsDoreMaliId != RowId && p.DoreMaliCode == _code);
                            if (q1.Any())
                            {
                                XtraMessageBox.Show("این کد قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                txtCode.Text = CodeBeforeEdit;
                                return false;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }
            ////////////////// اعتبار سنجی تکس باکس و کمبوباکس ها////////////
            if (string.IsNullOrEmpty(txtDoreMali.Text) || Convert.ToInt32(txtDoreMali.Text) < 1397)
            {
                XtraMessageBox.Show("دوره مالی باید بیشتر از 1396 باشد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else if (string.IsNullOrEmpty(cmbMajmoehaList.EditValue.ToString()) || string.IsNullOrEmpty(cmbVahedhaList.EditValue.ToString()) || string.IsNullOrEmpty(cmbShobeList.EditValue.ToString()))
            {
                XtraMessageBox.Show("لطفاً اطلاعات را کامل وارد کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        int _DoreMali = Convert.ToInt32(txtDoreMali.Text);
                        if (this.Text == "ایجاد رکورد جدید")
                        {
                            if (db.MsDoreMalis.Any())
                            {
                                var q1 = db.MsDoreMalis.Where(p => p.MsShobeId == _ShobeId && p.DoreMali == _DoreMali);
                                if (q1.Any())
                                {
                                    XtraMessageBox.Show("این دوره قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                    return false;
                                }
                            }
                        }
                        else if (this.Text == "ویرایش رکورد جاری")
                        {
                            var q1 = db.MsDoreMalis.Where(p => p.MsShobeId == _ShobeId && p.MsDoreMaliId != RowId && p.DoreMali == _DoreMali);
                            if (q1.Any())
                            {
                                XtraMessageBox.Show("این دوره قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                //txtDoreMali.Text = nameBeforeEdit;
                                return false;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }

            return true;
        }

        private void cmbMajmoehaList_EditValueChanged(object sender, EventArgs e)
        {
            FillcmbVahedhaList();
        }

        private void cmbVahedhaList_EditValueChanged(object sender, EventArgs e)
        {
            FillcmbShobehaList();
        }

        private void cmbMajmoehaList_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                cmbMajmoehaList.ShowPopup();
            }
            else
            {
                cmbMajmoehaList.ClosePopup();
            }

        }

        private void cmbVahedhaList_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                cmbVahedhaList.ShowPopup();
            }
            else
            {
                cmbVahedhaList.ClosePopup();
            }

        }

        private void cmbShobehaList_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                cmbShobeList.ShowPopup();
            }
            else
            {
                cmbShobeList.ClosePopup();
            }

        }

        private void FrmDorehaCed_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F2)
            {
                btnCreateClose_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F3)
            {
                btnCreateNext_Click(sender, null);
            }
            else if (e.KeyCode == Keys.Escape)
            {
                btnClose_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F7)
            {
                btnNewCode_Click(sender, null);
            }

        }

        private void cmbShobeList_EditValueChanged(object sender, EventArgs e)
        {
            _ShobeId = Convert.ToInt32(cmbShobeList.EditValue);
            FilltxtShobeCode();
        }

        private void chkEditCode_CheckedChanged(object sender, EventArgs e)
        {
            txtCode.ReadOnly = chkEditCode.Checked ? false : true;

        }

        private void txtDoreMali_Leave(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtDoreMali.Text) || Convert.ToInt32(txtDoreMali.Text) < 1397)
            {
                XtraMessageBox.Show("دوره مالی باید بیشتر از 1396 باشد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                txtDoreMali.Focus();
                return;
            }
            txtStartDore.Text = txtDoreMali.Text + "/" + "01/01";
            txtEndDore.Text = txtDoreMali.Text + "/" + "12/29";

        }
    }
}