/****************************** Ghost.github.io ******************************\
*	Module Name:	FrmSalMaliCed.cs
*	Project:		SystemManagement
*	Copyright (C) 2018 Kamal Khayati, All rights reserved.
*	This software may be modified and distributed under the terms of the MIT license.  See LICENSE file for details.
*
*	Written by Kamal Khayati <Kamal1355@gmail.com>,  2018 / 12 / 31   04:07 ب.ظ
*	
***********************************************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DBHesabdari_TG;
using HelpClassLibrary;
using System.Data.Entity;
using System.Globalization;

namespace SystemManagement.DafaterMali
{
    public partial class FrmSalhaCed : DevExpress.XtraEditors.XtraForm
    {
        FrmSalhaList Fm;
        public FrmSalhaCed(FrmSalhaList fm)
        {
            InitializeComponent();
            Fm = fm;
        }
        int _ShobeId = 0;
        public void FillcmbMajmoehaList()
        {
            //var db = new MyContext();
            //db.MsMajmoes.Where(s => s.IsActive == true).LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    msMajmoesBindingSource.DataSource = db.MsMajmoes.Local.ToBindingList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsMajmoes.Any())
                    {
                        // This line of code is generated by Data Source Configuration Wizard
                        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
                        db.MsMajmoes.Where(s => s.MajmoeIsActive == true).Load();
                        // Bind data to control when loading complete
                        msMajmoesBindingSource.DataSource = db.MsMajmoes.Local.ToBindingList();

                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
        public void FillcmbVahedhaList()
        {
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsVaheds.Any())
                    {
                        int _MajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                        // This line of code is generated by Data Source Configuration Wizard
                        db.MsVaheds.Where(s => s.VahedIsActive == true && s.MsMajmoeId == _MajmoeId).Load();
                        // Bind data to control when loading complete
                        msVahedsBindingSource.DataSource = db.MsVaheds.Local.ToBindingList();
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
        public void FillcmbShobehaList()
        {
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsVaheds.Any())
                    {
                        int _VahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                        // This line of code is generated by Data Source Configuration Wizard
                        db.MsShobes.Where(s => s.ShobeIsActive == true && s.MsVahedId == _VahedId).Load();
                        // Bind data to control when loading complete
                        msShobesBindingSource.DataSource = db.MsShobes.Local.ToBindingList();
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
        public void FilltxtShobeCode()
        {
            using (var db = new MyContext())
            {
                try
                {
                    if (msShobesBindingSource.DataSource!=null)
                    {
                        var q = db.MsShobes.FirstOrDefault(s => s.MsShobeId == _ShobeId);
                        if (q!=null)
                            txtShobeCode.Text = q.ShobeCode.ToString();

                        btnNewCode_Click(null, null);
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
        public void FillchkcmbPermissiveUsers()
        {
            using (var db = new MyContext())
            {
                try
                {
                    var q = db.RmsShobehaBmsUserhas.Where(s => s.MsShobeId == _ShobeId);
                    rmsShobehaBmsUserhasBindingSource.DataSource = null;
                    if (q.Any())
                    {
                        // Call the Load method to get the data for the given DbSet from the database.
                        q.Load();
                        // This line of code is generated by Data Source Configuration Wizard
                        rmsShobehaBmsUserhasBindingSource.DataSource = db.RmsShobehaBmsUserhas.Local.ToBindingList();
                        // This line of code is generated by Data Source Configuration Wizard
                        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
                        //db.MsUsers.Where(s => s.IsActive == true).LoadAsync().ContinueWith(loadTask =>
                        //{
                        //    // Bind data to control when loading complete
                        //    msUsersBindingSource.DataSource = db.MsUsers.Local.ToBindingList();
                        //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
                        chkcmbPermissiveUsers.Properties.DropDownRows = 10;
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            #region
            // Add check items to the control's dropdown.
            //string[] itemValues = new string[] 
            //{
            //  "Circle", "Rectangle", "Ellipse",
            //  "Triangle", "Square"
            //};
            //foreach (string value in itemValues)
            // checkedComboBoxEdit1.Properties.Items.Add(value, CheckState.Unchecked, true);
            // Set the edit value.
            //checkedComboBoxEdit1.SetEditValue("Circle; Ellipse");
            // Disable the Circle item.
            //checkedComboBoxEdit1.Properties.Items["Circle"].Enabled = false;
            #endregion

        }
        private void btnNewCode_Click(object sender, EventArgs e)
        {
            if (cmbShobeList.EditValue != null)
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        var q = db.MsSalMalis.Where(s => s.MsShobeId == _ShobeId);
                        if (q.Any())
                        {
                            var MaximumCod = q.Max(p => p.SalMaliCode);
                            txtCode.Text = (MaximumCod + 1).ToString().Substring(6);
                        }
                        else
                        {
                            txtCode.Text = "001";
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }

        }

        string CodeBeforeEdit = "";
        string NameBeforeEdit = "";
        int RowId = 0;
        private void FrmSalhaCed_Load(object sender, EventArgs e)
        {
            FillcmbMajmoehaList();
            if (this.Text != "ایجاد رکورد جدید")
            {
                cmbMajmoehaList.EditValue = Convert.ToInt32(Fm.gridView1.GetFocusedRowCellValue("MsMajmoeId").ToString());
                cmbVahedhaList.EditValue = Convert.ToInt32(Fm.gridView1.GetFocusedRowCellValue("MsVahedId").ToString());
                cmbShobeList.EditValue = Convert.ToInt32(Fm.gridView1.GetFocusedRowCellValue("MsShobeId").ToString());
                txtId.Text = Fm.gridView1.GetFocusedRowCellValue("MsSalMaliId").ToString();
                txtCode.Text = Fm.gridView1.GetFocusedRowCellValue("SalMaliCode").ToString().Substring(6);
                txtSalMali.Text = Fm.gridView1.GetFocusedRowCellValue("SalMali").ToString();
                txtStartSal.EditValue = Fm.gridView1.GetFocusedRowCellValue("StartSalMali").ToString().Substring(0,10);
                txtEndSal.EditValue = Fm.gridView1.GetFocusedRowCellValue("EndSalMali").ToString().Substring(0, 10); 
                chkIsActive.Checked = Convert.ToBoolean(Fm.gridView1.GetFocusedRowCellValue("SalMaliIsActive"));
                chkSalIsDefault.Checked = Convert.ToBoolean(Fm.gridView1.GetFocusedRowCellValue("SalIsDefault"));
                chkSalIsClose.Checked = Convert.ToBoolean(Fm.gridView1.GetFocusedRowCellValue("SalIsClose"));
                txtMaliat.Text = Fm.gridView1.GetFocusedRowCellValue("Maliat").ToString();
                txtAvarez.Text = Fm.gridView1.GetFocusedRowCellValue("Avarez").ToString();

                CodeBeforeEdit = txtCode.Text;
                NameBeforeEdit = txtSalMali.Text;
                RowId = Convert.ToInt32(txtId.Text);

                using (var db = new MyContext())
                {
                    try
                    {
                        var q = db.RmsSalMalihaBmsUserhas.Where(s => s.MsSalMaliId == RowId).Select(s => s.MsUserId).ToList();

                        string CheckedItems = string.Empty;
                        foreach (var item in q)
                            CheckedItems += item.ToString() + ",";

                        chkcmbPermissiveUsers.SetEditValue(CheckedItems);

                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                            "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }
            else
            {
                HelpClass1.SetCurrentYear(txtSalMali);
                txtStartSal.Text = txtSalMali.Text + "/" + "01/01";
                txtEndSal.Text = txtSalMali.Text + "/" + "12/29";
            }
        }

        private void btnCreateNext_Click(object sender, EventArgs e)
        {
            btnCreateCloseClicked = false;
            btnCreateClose_Click(null, null);
            btnCreateCloseClicked = true;

        }

        bool btnCreateCloseClicked = true;
        private void btnCreateClose_Click(object sender, EventArgs e)
        {

            if (TextEditValidation())
            {
                btnCreateClose.Enabled = false;
                btnCreateNext.Enabled = false;
                if (this.Text == "ایجاد رکورد جدید")
                {
                    using (var db = new MyContext())
                    {
                        try
                        {
                            MsSalMali obj = new MsSalMali();
                            obj.SalMaliCode = Convert.ToInt32(txtShobeCode.Text + txtCode.Text);
                            obj.SalMali = txtSalMali.Text;
                            obj.StartSalMali = Convert.ToDateTime(txtStartSal.Text);
                            obj.EndSalMali = Convert.ToDateTime(txtEndSal.Text);
                            obj.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                            obj.MajmoeName = cmbMajmoehaList.Text;
                            obj.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                            obj.VahedName = cmbVahedhaList.Text;
                            obj.MsShobeId = Convert.ToInt32(cmbShobeList.EditValue);
                            obj.ShobeName = cmbShobeList.Text;
                            obj.PermissiveUsers = chkcmbPermissiveUsers.Text;
                            obj.SalMaliIsActive = chkIsActive.Checked;
                            obj.SalIsDefault = chkSalIsDefault.Checked;
                            obj.SalIsClose = chkSalIsClose.Checked;
                            obj.Maliat = Convert.ToDecimal(txtMaliat.Text != "" ? txtMaliat.Text : "0");
                            obj.Avarez = Convert.ToDecimal(txtAvarez.Text != "" ? txtAvarez.Text : "0");
                            db.MsSalMalis.Add(obj);
                            db.SaveChanges();
                            /////////////////////////////////////////////////////////////////////////////////////
                            int _code = Convert.ToInt32(txtShobeCode.Text + txtCode.Text);
                            var q = db.MsSalMalis.FirstOrDefault(s => s.SalMaliCode == _code);

                            if (rmsShobehaBmsUserhasBindingSource.DataSource != null)
                            {
                                var CheckedList = chkcmbPermissiveUsers.Properties.GetItems().GetCheckedValues();
                                if (CheckedList != null)
                                {
                                    foreach (var item in CheckedList)
                                    {
                                        RmsSalMalihaBmsUserha obj1 = new RmsSalMalihaBmsUserha();
                                        obj1.MsSalMaliId = q.MsSalMaliId;
                                        obj1.SalMali = q.SalMali;
                                        obj1.MsUserId = Convert.ToInt32(item.ToString());
                                        int id = Convert.ToInt32(item.ToString());
                                        var q1 = db.MsUsers.FirstOrDefault(s => s.MsUserId == id);
                                        obj1.UserName = q1.UserName;
                                        obj1.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                        obj1.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                                        obj1.MsShobeId = Convert.ToInt32(cmbShobeList.EditValue);

                                        db.RmsSalMalihaBmsUserhas.Add(obj1);
                                    }
                                }
                            }

                            db.SaveChanges();

                            Fm.btnDisplyActiveList_ItemClick(null, null);
                            XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                            Fm.gridView1.MoveLast();
                            if (btnCreateCloseClicked)
                                this.Close();
                            else
                            {
                                btnCreateClose.Enabled = true;
                                btnCreateNext.Enabled = true;
                                btnNewCode_Click(null, null);
                                txtSalMali.Text = "";
                                txtStartSal.Text = "";
                                txtEndSal.Text = "";
                                chkcmbPermissiveUsers.SetEditValue("");
                                chkSalIsDefault.Checked = false;
                                chkSalIsClose.Checked = false;
                                txtMaliat.Text = "";
                                txtAvarez.Text = "";
                                txtSalMali.Focus();
                            }
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.ToString(), "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
                else if (this.Text == "ویرایش رکورد جاری")
                {
                    using (var db = new MyContext())
                    {
                        try
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q = db.MsSalMalis.FirstOrDefault(p => p.MsSalMaliId == RowId);
                            if (q != null)
                            {
                                q.SalMaliCode = Convert.ToInt32(txtShobeCode.Text + txtCode.Text);
                                q.SalMali = txtSalMali.Text;
                                q.StartSalMali = Convert.ToDateTime(txtStartSal.Text);
                                q.EndSalMali = Convert.ToDateTime(txtEndSal.Text);
                                q.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                q.MajmoeName = cmbMajmoehaList.Text;
                                q.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                                q.VahedName = cmbVahedhaList.Text;
                                q.MsShobeId = Convert.ToInt32(cmbShobeList.EditValue);
                                q.ShobeName = cmbShobeList.Text;
                                q.PermissiveUsers = chkcmbPermissiveUsers.Text;
                                q.SalMaliIsActive = chkIsActive.Checked;
                                q.SalIsDefault = chkSalIsDefault.Checked;
                                q.SalIsClose = chkSalIsClose.Checked;
                                q.Maliat = Convert.ToDecimal(txtMaliat.Text);
                                q.Avarez = Convert.ToDecimal(txtAvarez.Text);
                                /////////////////////////////////////////////////////////////////////////////////////
                                if (rmsShobehaBmsUserhasBindingSource.DataSource != null)
                                {
                                    var CheckedList = chkcmbPermissiveUsers.Properties.GetItems().GetCheckedValues();
                                    var q2 = db.RmsSalMalihaBmsUserhas.Where(s => s.MsSalMaliId == RowId).ToList();
                                    if (q2.Count > 0)
                                        db.RmsSalMalihaBmsUserhas.RemoveRange(q2);
                                    //////////////////////////////////////////////
                                    if (CheckedList != null)
                                    {
                                        foreach (var item in CheckedList)
                                        {
                                            RmsSalMalihaBmsUserha obj1 = new RmsSalMalihaBmsUserha();
                                            obj1.MsSalMaliId = q.MsSalMaliId;
                                            obj1.SalMali = q.SalMali;
                                            obj1.MsUserId = Convert.ToInt32(item.ToString());
                                            int id = Convert.ToInt32(item.ToString());
                                            var q1 = db.MsUsers.FirstOrDefault(s => s.MsUserId == id);
                                            obj1.UserName = q1.UserName;
                                            obj1.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                            obj1.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                                            obj1.MsShobeId = Convert.ToInt32(cmbShobeList.EditValue);

                                            db.RmsSalMalihaBmsUserhas.Add(obj1);
                                        }
                                    }
                                }

                                db.SaveChanges();

                                Fm.btnDisplyActiveList_ItemClick(null, null);
                                XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                this.Close();
                                Fm.gridView1.FocusedRowHandle = HelpClass1.EditRowIndex;
                            }
                            else
                                XtraMessageBox.Show("رکورد جاری در بانک اطلاعاتی موجود نیست", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
                else if (this.Text == "حذف رکورد جاری")
                {
                    using (var db = new MyContext())
                    {
                        try
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q = db.MsSalMalis.FirstOrDefault(p => p.MsSalMaliId == RowId);
                            if (q != null)
                            {
                                var q1 = db.RmsSalMalihaBmsUserhas.Where(s => s.MsSalMaliId == RowId).ToList();
                                if (q1.Count > 0)
                                    db.RmsSalMalihaBmsUserhas.RemoveRange(q1);
                                //////////////////////////////////////////////////////////////////////////////////
                                db.MsSalMalis.Remove(q);
                                db.SaveChanges();

                                Fm.btnDisplyActiveList_ItemClick(null, null);
                                XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                this.Close();
                                Fm.gridView1.FocusedRowHandle = HelpClass1.EditRowIndex - 1;
                            }
                            else
                                XtraMessageBox.Show("رکورد جاری در بانک اطلاعاتی موجود نیست", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
            }

        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();

        }

        private bool TextEditValidation()
        {
            ///////////////// اعتبار سنجی کد ////////////////////////////////////
            if (string.IsNullOrEmpty(txtCode.Text))
            {
                XtraMessageBox.Show("لطفا کد را وارد کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else if (Convert.ToInt32(txtCode.Text) == 0)
            {
                XtraMessageBox.Show("کد وارده باید عددی بزرگتر از صفر باشد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                if (this.Text == "ایجاد رکورد جدید")
                {
                    btnNewCode_Click(null, null);
                }
                else
                {
                    txtCode.Text = CodeBeforeEdit;
                }

                return false;
            }
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        int _code = Convert.ToInt32(txtShobeCode.Text + txtCode.Text);
                        if (this.Text == "ایجاد رکورد جدید")
                        {
                            if (db.MsSalMalis.Any())
                            {
                                var q1 = db.MsSalMalis.Where(p => p.SalMaliCode == _code);
                                if (q1.Any())
                                {
                                    XtraMessageBox.Show("این کد قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                    btnNewCode_Click(null, null);
                                    return false;
                                }
                            }
                        }
                        else if (this.Text == "ویرایش رکورد جاری")
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q1 = db.MsSalMalis.Where(p => p.MsSalMaliId != RowId && p.SalMaliCode == _code);
                            if (q1.Any())
                            {
                                XtraMessageBox.Show("این کد قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                txtCode.Text = CodeBeforeEdit;
                                return false;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }
            ////////////////// اعتبار سنجی تکس باکس و کمبوباکس ها////////////
            if (string.IsNullOrEmpty(txtSalMali.Text) || Convert.ToInt32(txtSalMali.Text) < 1397)
            {
                XtraMessageBox.Show("دوره مالی باید بیشتر از 1396 باشد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else if (string.IsNullOrEmpty(cmbMajmoehaList.EditValue.ToString()) || string.IsNullOrEmpty(cmbVahedhaList.EditValue.ToString()) || string.IsNullOrEmpty(cmbShobeList.EditValue.ToString()))
            {
                XtraMessageBox.Show("لطفاً اطلاعات را کامل وارد کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        if (this.Text == "ایجاد رکورد جدید")
                        {
                            if (db.MsSalMalis.Any())
                            {
                                var q1 = db.MsSalMalis.Where(p => p.MsShobeId == _ShobeId && p.SalMali==txtSalMali.Text);
                                if (q1.Any())
                                {
                                    XtraMessageBox.Show("این دوره قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                    return false;
                                }
                            }
                        }
                        else if (this.Text == "ویرایش رکورد جاری")
                        {
                            var q1 = db.MsSalMalis.Where(p => p.MsShobeId == _ShobeId && p.MsSalMaliId != RowId && p.SalMali == txtSalMali.Text);
                            if (q1.Any())
                            {
                                XtraMessageBox.Show("این دوره قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                //txtSalMali.Text = nameBeforeEdit;
                                return false;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }

            return true;
        }

        private void cmbListMajmoeha_EditValueChanged(object sender, EventArgs e)
        {
            FillcmbVahedhaList();
        }

        private void cmbVahedhaList_EditValueChanged(object sender, EventArgs e)
        {
            FillcmbShobehaList();
        }

        private void cmbMajmoehaList_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                cmbMajmoehaList.ShowPopup();
            }
            else
            {
                cmbMajmoehaList.ClosePopup();
            }

        }

        private void cmbVahedhaList_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                cmbVahedhaList.ShowPopup();
            }
            else
            {
                cmbVahedhaList.ClosePopup();
            }

        }

        private void cmbShobehaList_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                cmbShobeList.ShowPopup();
            }
            else
            {
                cmbShobeList.ClosePopup();
            }

        }

        private void chkcmbPermissiveUsers_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                chkcmbPermissiveUsers.ShowPopup();
            }
            else
            {
                chkcmbPermissiveUsers.ClosePopup();
            }

        }

        private void FrmSalhaCed_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F2)
            {
                btnCreateClose_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F3)
            {
                btnCreateNext_Click(sender, null);
            }
            else if (e.KeyCode == Keys.Escape)
            {
                btnClose_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F7)
            {
                btnNewCode_Click(sender, null);
            }

        }

        private void cmbShobeList_EditValueChanged(object sender, EventArgs e)
        {
            _ShobeId = Convert.ToInt32(cmbShobeList.EditValue);
            FilltxtShobeCode();
            FillchkcmbPermissiveUsers();

        }

        private void chkEditCode_CheckedChanged(object sender, EventArgs e)
        {
            txtCode.ReadOnly = chkEditCode.Checked ? false : true;

        }

        private void txtSalMali_Leave(object sender, EventArgs e)
        {
            if (string.IsNullOrEmpty(txtSalMali.Text) || Convert.ToInt32(txtSalMali.Text) < 1397)
            {
                XtraMessageBox.Show("دوره مالی باید بیشتر از 1396 باشد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                txtSalMali.Focus();
                return;
            }
            txtStartSal.Text = txtSalMali.Text + "/" + "01/01";
            txtEndSal.Text = txtSalMali.Text + "/" + "12/29";

        }
    }
}