/****************************** Ghost.github.io ******************************\
*	Module Name:	FrmShoabatCed.cs
*	Project:		SystemManagement
*	Copyright (C) 2018 Kamal Khayati, All rights reserved.
*	This software may be modified and distributed under the terms of the MIT license.  See LICENSE file for details.
*
*	Written by Kamal Khayati <Kamal1355@gmail.com>,  2018 / 12 / 31   04:11 ب.ظ
*	
***********************************************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using HelpClassLibrary;
using DBHesabdari_TG;
using System.Data.Entity.Infrastructure;

namespace SystemManagement.DafaterMali
{
    public partial class FrmShoabatCed : DevExpress.XtraEditors.XtraForm
    {
        FrmShoabatList Fm;
        public FrmShoabatCed(FrmShoabatList fm)
        {
            InitializeComponent();
            Fm = fm;
        }
        public void FillcmbMajmoehaList()
        {
            //var db = new MyContext();
            //db.MsMajmoes.Where(s => s.IsActive == true).LoadAsync().ContinueWith(loadTask =>
            //{
            //    // Bind data to control when loading complete
            //    msMajmoesBindingSource.DataSource = db.MsMajmoes.Local.ToBindingList();
            //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsMajmoes.Any())
                    {
                        // This line of code is generated by Data Source Configuration Wizard
                        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
                        db.MsMajmoes.Where(s => s.MajmoeIsActive == true).Load();
                        // Bind data to control when loading complete
                        msMajmoesBindingSource.DataSource = db.MsMajmoes.Local.ToBindingList();

                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
        public void FillcmbVahedhaList()
        {
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsVaheds.Any())
                    {
                        int _MajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                        // This line of code is generated by Data Source Configuration Wizard
                        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
                        db.MsVaheds.Where(s => s.VahedIsActive == true && s.MsMajmoeId == _MajmoeId).Load();
                        // Bind data to control when loading complete
                        msVahedsBindingSource.DataSource = db.MsVaheds.Local.ToBindingList();
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }
        public void FilltxtVahedCode()
        {
            using (var db = new MyContext())
            {
                try
                {
                    if (db.MsVaheds.Any())
                    {
                        int _VahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                        var q = db.MsVaheds.FirstOrDefault(s => s.MsVahedId == _VahedId).VahedCode;
                        if (q > 0)
                            txtVahedCode.Text = q.ToString();

                        btnNewCode_Click(null, null);
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
        public void FillchkcmbPermissiveUsers()
        {
            using (var db = new MyContext())
            {
                try
                {
                    int _VahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                    var q = db.RmsVahedhaBmsUserhas.Where(s => s.MsVahedId == _VahedId);
                    rmsVahedhaBmsUserhasBindingSource.DataSource = null;
                    if (q.Any())
                    {
                        // Call the Load method to get the data for the given DbSet from the database.
                        q.Load();
                        // This line of code is generated by Data Source Configuration Wizard
                        rmsVahedhaBmsUserhasBindingSource.DataSource = db.RmsVahedhaBmsUserhas.Local.ToBindingList();
                        // This line of code is generated by Data Source Configuration Wizard
                        // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
                        //db.MsUsers.Where(s => s.IsActive == true).LoadAsync().ContinueWith(loadTask =>
                        //{
                        //    // Bind data to control when loading complete
                        //    msUsersBindingSource.DataSource = db.MsUsers.Local.ToBindingList();
                        //}, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
                        chkcmbPermissiveUsers.Properties.DropDownRows = 10;
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            #region
            // Add check items to the control's dropdown.
            //string[] itemValues = new string[] 
            //{
            //  "Circle", "Rectangle", "Ellipse",
            //  "Triangle", "Square"
            //};
            //foreach (string value in itemValues)
            // checkedComboBoxEdit1.Properties.Items.Add(value, CheckState.Unchecked, true);
            // Set the edit value.
            //checkedComboBoxEdit1.SetEditValue("Circle; Ellipse");
            // Disable the Circle item.
            //checkedComboBoxEdit1.Properties.Items["Circle"].Enabled = false;
            #endregion

        }
        private void btnNewCode_Click(object sender, EventArgs e)
        {
            if (cmbVahedhaList.EditValue != null)
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        int _VahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                        var q = db.MsShobes.Where(s => s.MsVahedId == _VahedId);
                        if (q.Any())
                        {
                            var MaximumCod = q.Max(p => p.ShobeCode);
                            txtCode.Text = (MaximumCod + 1).ToString().Substring(4);
                        }
                        else
                        {
                            txtCode.Text = "01";
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }

        }

        string CodeBeforeEdit = "";
        string NameBeforeEdit = "";
        string PermissiveUsersBeforeEdit = "";
        private void FrmShobehaCed_Load(object sender, EventArgs e)
        {
            FillcmbMajmoehaList();

            if (this.Text != "ایجاد رکورد جدید")
            {
                cmbMajmoehaList.EditValue = Convert.ToInt32(Fm.gridView1.GetFocusedRowCellValue("MsMajmoeId").ToString());
                cmbVahedhaList.EditValue = Convert.ToInt32(Fm.gridView1.GetFocusedRowCellValue("MsVahedId").ToString());
                txtId.Text = Fm.gridView1.GetFocusedRowCellValue("MsShobeId").ToString();
                txtCode.Text = Fm.gridView1.GetFocusedRowCellValue("ShobeCode").ToString().Substring(4);
                txtName.Text = Fm.gridView1.GetFocusedRowCellValue("ShobeName").ToString();
                chkIsActive.Checked = Convert.ToBoolean(Fm.gridView1.GetFocusedRowCellValue("ShobeIsActive"));


                int RowId = Convert.ToInt32(txtId.Text);
                using (var db = new MyContext())
                {
                    try
                    {
                        var q = db.RmsShobehaBmsUserhas.Where(s => s.MsShobeId == RowId).Select(s => s.MsUserId).ToList();

                        string CheckedItems = string.Empty;
                        foreach (var item in q)
                            CheckedItems += item.ToString() + ",";

                        chkcmbPermissiveUsers.SetEditValue(CheckedItems);
                        /////////////////////////////////////////////////////////////////////
                        var q4 = db.MsInfoOthers.FirstOrDefault(s => s.MsShobeId == RowId);
                        if (q4 != null)
                        {
                            if (q4.NoeShakhs == "حقیقی") radioButton1.Checked = true; else radioButton2.Checked = true;
                            txtNoeFaaliat.Text = q4.NoeFaaliat.ToString();
                            txtAdress.Text = q4.Adress.ToString();
                            txtCodePosti.Text = q4.CodePosti.ToString();
                            txtSandoghPosti.Text = q4.SandoghPosti.ToString();
                            txtShomarePlak.Text = q4.ShomarePlak.ToString();
                            txtShomareSabt.Text = q4.ShomareSabt.ToString();
                            txtCodeMelli.Text = q4.CodeMelli.ToString();
                            txtShenaseMelli.Text = q4.ShenaseMelli.ToString();
                            txtCodeSenfee.Text = q4.CodeSenfee.ToString();
                            txtCodeEghtesadi.Text = q4.CodeEghtesadi.ToString();
                            txtTell1.Text = q4.Tell1.ToString();
                            txtTell2.Text = q4.Tell2.ToString();
                            txtTellFax1.Text = q4.TellFax1.ToString();
                            txtTellFax2.Text = q4.TellFax2.ToString();
                            txtMobile1.Text = q4.Mobile1.ToString();
                            txtMobile2.Text = q4.Mobile2.ToString();
                            txtEmail1.Text = q4.Email1.ToString();
                            txtEmail2.Text = q4.Email2.ToString();
                            txtSite.Text = q4.Site.ToString();
                            txtWebLog.Text = q4.WebLog.ToString();
                            txtShabakeEjtemaee1.Text = q4.ShabakeEjtemaee1.ToString();
                            txtShabakeEjtemaee2.Text = q4.ShabakeEjtemaee2.ToString();
                            txtShParvandeMaliati.Text = q4.ShParvandeMaliati.ToString();
                            txtShBimeKargah.Text = q4.ShBimeKargah.ToString();
                        }

                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                            "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

                CodeBeforeEdit = txtCode.Text;
                NameBeforeEdit = txtName.Text;
                PermissiveUsersBeforeEdit = chkcmbPermissiveUsers.Text;
            }

        }

        private void btnCreateNext_Click(object sender, EventArgs e)
        {
            btnCreateClose_Clicked = false;
            btnCreateClose_Click(null, null);
            btnCreateClose_Clicked = true;

        }

        bool btnCreateClose_Clicked = true;
        private void btnCreateClose_Click(object sender, EventArgs e)
        {

            if (TextEditValidation())
            {
                btnCreateClose.Enabled = false;
                btnCreateNext.Enabled = false;
                if (this.Text == "ایجاد رکورد جدید")
                {
                    using (var db = new MyContext())
                    {
                        try
                        {
                            MsShobe obj = new MsShobe()
                            {
                                ShobeCode = Convert.ToInt32(txtVahedCode.Text + txtCode.Text),
                                ShobeName = txtName.Text,
                                ShobeIsActive = chkIsActive.Checked,
                                MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue),
                                MajmoeName = cmbMajmoehaList.Text,
                                MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue),
                                VahedName = cmbVahedhaList.Text,
                                PermissiveUsers = chkcmbPermissiveUsers.Text,
                            };
                            db.MsShobes.Add(obj);
                            db.SaveChanges();
                            /////////////////////////////////////////////////////////////////////////////////////
                            int _code = Convert.ToInt32(txtVahedCode.Text + txtCode.Text);
                            var q = db.MsShobes.FirstOrDefault(s => s.ShobeCode == _code);

                            if (rmsVahedhaBmsUserhasBindingSource.DataSource != null)
                            {
                                var CheckedList = chkcmbPermissiveUsers.Properties.GetItems().GetCheckedValues();
                                if (CheckedList != null)
                                {
                                    foreach (var item in CheckedList)
                                    {
                                        RmsShobehaBmsUserha obj1 = new RmsShobehaBmsUserha();
                                        obj1.MsShobeId = q.MsShobeId;
                                        obj1.ShobeName = q.ShobeName;
                                        obj1.MsUserId = Convert.ToInt32(item.ToString());
                                        int id = Convert.ToInt32(item.ToString());
                                        var q1 = db.MsUsers.FirstOrDefault(s => s.MsUserId == id);
                                        obj1.UserName = q1.UserName;
                                        obj1.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                        obj1.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);

                                        db.RmsShobehaBmsUserhas.Add(obj1);
                                    }
                                }
                            }
                            ///////////////////////////////////////////////////////////////////////////////////////
                            MsInfoOther obj2 = new MsInfoOther()
                            {
                                MsShobeId = q.MsShobeId,
                                MsCode = _code,
                                MsName = txtName.Text,
                                NoeShakhs = radioButton1.Checked ? "حقیقی" : "حقوقی",
                                NoeFaaliat = txtNoeFaaliat.Text,
                                Adress = txtAdress.Text,
                                CodePosti = txtCodePosti.Text,
                                SandoghPosti = txtSandoghPosti.Text,
                                ShomarePlak = txtShomarePlak.Text,
                                ShomareSabt = txtShomareSabt.Text,
                                CodeMelli = txtCodeMelli.Text,
                                ShenaseMelli = txtShenaseMelli.Text,
                                CodeSenfee = txtCodeSenfee.Text,
                                CodeEghtesadi = txtCodeEghtesadi.Text,
                                Tell1 = txtTell1.Text,
                                Tell2 = txtTell2.Text,
                                TellFax1 = txtTellFax1.Text,
                                TellFax2 = txtTellFax2.Text,
                                Mobile1 = txtMobile1.Text,
                                Mobile2 = txtMobile2.Text,
                                Email1 = txtEmail1.Text,
                                Email2 = txtEmail2.Text,
                                Site = txtSite.Text,
                                WebLog = txtWebLog.Text,
                                ShabakeEjtemaee1 = txtShabakeEjtemaee1.Text,
                                ShabakeEjtemaee2 = txtShabakeEjtemaee2.Text,
                                ShParvandeMaliati = txtShParvandeMaliati.Text,
                                ShBimeKargah = txtShBimeKargah.Text,
                            };
                            db.MsInfoOthers.Add(obj2);

                            db.SaveChanges();

                            Fm.btnDisplyActiveList_ItemClick(null, null);
                            XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                            Fm.gridView1.MoveLast();
                            if (btnCreateClose_Clicked)
                                this.Close();
                            else
                            {
                                btnCreateClose.Enabled = true;
                                btnCreateNext.Enabled = true;
                                cmbMajmoehaList.EditValue = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                btnNewCode_Click(null, null);
                                txtName.Text = "";
                                chkcmbPermissiveUsers.SetEditValue("");
                                HelpClass1.ClearTextEditControlsText(xtraScrollableControl1);
                                txtName.Focus();
                            }
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
                else if (this.Text == "ویرایش رکورد جاری")
                {
                    using (var db = new MyContext())
                    {
                        try
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q = db.MsShobes.FirstOrDefault(p => p.MsShobeId == RowId);
                            if (q != null)
                            {
                                q.ShobeCode = Convert.ToInt32(txtVahedCode.Text + txtCode.Text);
                                q.ShobeName = txtName.Text;
                                q.ShobeIsActive = chkIsActive.Checked;
                                q.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                q.MajmoeName = cmbMajmoehaList.Text;
                                q.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                                q.VahedName = cmbVahedhaList.Text;
                                q.PermissiveUsers = chkcmbPermissiveUsers.Text;

                                /////////////////////////////متد اصلاح کد و نام شعبه در زیر شاخه های بالاتر WillCascadeOnUpdate ///////////////////////
                                if (CodeBeforeEdit != txtCode.Text || NameBeforeEdit != txtName.Text)
                                {
                                    /////////////////////////// WillCascadeOnUpdate : MsDoreMalis /////////////////////////
                                    var q7 = db.MsDoreMalis.Where(s=>s.MsShobeId == RowId).ToList();
                                    if (q7.Count > 0)
                                    {
                                        foreach (var item in q7)
                                        {
                                            string a = item.DoreMaliCode.ToString().Substring(0, 4);
                                            string b = item.DoreMaliCode.ToString().Substring(4, 2);
                                            string c = item.DoreMaliCode.ToString().Substring(6, 3);
                                            string _txtName = item.ShobeName.ToString();

                                            if (a != txtCode.Text || _txtName != txtName.Text)
                                            {
                                                item.DoreMaliCode = Convert.ToInt32(a + txtCode.Text + c);
                                                item.ShobeName = txtName.Text;
                                            }
                                        }
                                    }
                                }
                                /////////////////////////////متد جلوگیری از حذف دسترسی کاربران به زیر شاخه های بالاتر WillCascadeOnUpdate : RmsShobehaBmsUserhas && RmsDoreMalihaBmsUserhas////////////
                                if (PermissiveUsersBeforeEdit != chkcmbPermissiveUsers.Text && rmsVahedhaBmsUserhasBindingSource.DataSource != null)
                                {
                                    var CheckedList = chkcmbPermissiveUsers.Properties.GetItems().GetCheckedValues();
                                    var q10 = db.RmsDoreMalihaBmsUserhas.Where(s => s.MsShobeId == RowId).ToList();
                                    string Error = "عملیات با خطا مواجه شد \n تغییر در کاربران مجاز مقدور نیست \n جهت اعمال تغییر بایستی : \n";

                                    if (q10.Count > 0)
                                    {
                                        foreach (var item in q10)
                                        {
                                            if (!CheckedList.Contains(item.MsUserId))
                                            {
                                                Error += "دسترسی (" + item.UserName + ") را از سال مالی (" + item.DoreMaliName + ") خارج کنید \n";
                                            }
                                        }
                                    }
                                    if (Error != "عملیات با خطا مواجه شد \n تغییر در کاربران مجاز مقدور نیست \n جهت اعمال تغییر بایستی : \n")
                                    {
                                        XtraMessageBox.Show(Error, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                        return;
                                    }
                                    //////////////////تغییر و یا ویرایش کاربران مجاز در لیست شعبه ها بصورت حذف از دیتابیس و درج در دیتابیس/////////////
                                    ///////////////////////////////////حذف از دیتابیس////////////////////////////////////////
                                    var q1 = db.RmsShobehaBmsUserhas.Where(s => s.MsShobeId == RowId).ToList();
                                    if (q1.Count > 0)
                                        db.RmsShobehaBmsUserhas.RemoveRange(q1);
                                    //////////////////////////////////درج در دیتابیس/////////////////////////////////////////
                                    if (CheckedList != null)
                                    {
                                        foreach (var item in CheckedList)
                                        {
                                            RmsShobehaBmsUserha obj1 = new RmsShobehaBmsUserha();
                                            obj1.MsShobeId = q.MsShobeId;
                                            obj1.ShobeName = q.ShobeName;
                                            obj1.MsUserId = Convert.ToInt32(item.ToString());
                                            int id = Convert.ToInt32(item.ToString());
                                            var q2 = db.MsUsers.FirstOrDefault(s => s.MsUserId == id);
                                            obj1.UserName = q2.UserName;
                                            obj1.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                            obj1.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                                            db.RmsShobehaBmsUserhas.Add(obj1);
                                        }
                                    }
                                }
                                /////////////////////////////////////////////////////////////////////////////
                                int _code = Convert.ToInt32(txtVahedCode.Text + txtCode.Text);
                                var q4 = db.MsInfoOthers.FirstOrDefault(s => s.MsShobeId == RowId);
                                if (q4 != null)
                                {

                                    q4.MsShobeId = RowId;
                                    q4.MsCode = _code;
                                    q4.MsName = txtName.Text;
                                    q4.NoeShakhs = radioButton1.Checked ? "حقیقی" : "حقوقی";
                                    q4.NoeFaaliat = txtNoeFaaliat.Text;
                                    q4.Adress = txtAdress.Text;
                                    q4.CodePosti = txtCodePosti.Text;
                                    q4.SandoghPosti = txtSandoghPosti.Text;
                                    q4.ShomarePlak = txtShomarePlak.Text;
                                    q4.ShomareSabt = txtShomareSabt.Text;
                                    q4.CodeMelli = txtCodeMelli.Text;
                                    q4.ShenaseMelli = txtShenaseMelli.Text;
                                    q4.CodeSenfee = txtCodeSenfee.Text;
                                    q4.CodeEghtesadi = txtCodeEghtesadi.Text;
                                    q4.Tell1 = txtTell1.Text;
                                    q4.Tell2 = txtTell2.Text;
                                    q4.TellFax1 = txtTellFax1.Text;
                                    q4.TellFax2 = txtTellFax2.Text;
                                    q4.Mobile1 = txtMobile1.Text;
                                    q4.Mobile2 = txtMobile2.Text;
                                    q4.Email1 = txtEmail1.Text;
                                    q4.Email2 = txtEmail2.Text;
                                    q4.Site = txtSite.Text;
                                    q4.WebLog = txtWebLog.Text;
                                    q4.ShabakeEjtemaee1 = txtShabakeEjtemaee1.Text;
                                    q4.ShabakeEjtemaee2 = txtShabakeEjtemaee2.Text;
                                    q4.ShParvandeMaliati = txtShParvandeMaliati.Text;
                                    q4.ShBimeKargah = txtShBimeKargah.Text;
                                }
                                else
                                {
                                    MsInfoOther obj2 = new MsInfoOther()
                                    {
                                        MsShobeId = RowId,
                                        MsCode = _code,
                                        MsName = txtName.Text,
                                        NoeShakhs = radioButton1.Checked ? "حقیقی" : "حقوقی",
                                        NoeFaaliat = txtNoeFaaliat.Text,
                                        Adress = txtAdress.Text,
                                        CodePosti = txtCodePosti.Text,
                                        SandoghPosti = txtSandoghPosti.Text,
                                        ShomarePlak = txtShomarePlak.Text,
                                        ShomareSabt = txtShomareSabt.Text,
                                        CodeMelli = txtCodeMelli.Text,
                                        ShenaseMelli = txtShenaseMelli.Text,
                                        CodeSenfee = txtCodeSenfee.Text,
                                        CodeEghtesadi = txtCodeEghtesadi.Text,
                                        Tell1 = txtTell1.Text,
                                        Tell2 = txtTell2.Text,
                                        TellFax1 = txtTellFax1.Text,
                                        TellFax2 = txtTellFax2.Text,
                                        Mobile1 = txtMobile1.Text,
                                        Mobile2 = txtMobile2.Text,
                                        Email1 = txtEmail1.Text,
                                        Email2 = txtEmail2.Text,
                                        Site = txtSite.Text,
                                        WebLog = txtWebLog.Text,
                                        ShabakeEjtemaee1 = txtShabakeEjtemaee1.Text,
                                        ShabakeEjtemaee2 = txtShabakeEjtemaee2.Text,
                                        ShParvandeMaliati = txtShParvandeMaliati.Text,
                                        ShBimeKargah = txtShBimeKargah.Text,
                                    };
                                    db.MsInfoOthers.Add(obj2);
                                }

                                db.SaveChanges();

                                Fm.btnDisplyActiveList_ItemClick(null, null);
                                XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                this.Close();
                                Fm.gridView1.FocusedRowHandle = HelpClass1.EditRowIndex;
                            }
                            else
                                XtraMessageBox.Show("رکورد جاری در بانک اطلاعاتی موجود نیست", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
                else if (this.Text == "حذف رکورد جاری")
                {
                    using (var db = new MyContext())
                    {
                        try
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q = db.MsShobes.FirstOrDefault(p => p.MsShobeId == RowId);
                            if (q != null)
                            {
                                var q1 = db.RmsShobehaBmsUserhas.Where(s => s.MsShobeId == RowId).ToList();
                                if (q1.Count > 0)
                                    db.RmsShobehaBmsUserhas.RemoveRange(q1);
                                //////////////////////////////////////////////////////////////////////////////////
                                q.ShobeCode = Convert.ToInt32(txtVahedCode.Text + txtCode.Text.ToString());
                                q.ShobeName = txtName.Text;
                                q.ShobeIsActive = chkIsActive.Checked;
                                q.MsMajmoeId = Convert.ToInt32(cmbMajmoehaList.EditValue);
                                q.MajmoeName = cmbMajmoehaList.Text;
                                q.MsVahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
                                q.VahedName = cmbVahedhaList.Text;
                                q.PermissiveUsers = chkcmbPermissiveUsers.Text;

                                db.MsShobes.Remove(q);
                                //////////////////////////////////////////////////////////////////////////////////
                                int _code = Convert.ToInt32(txtVahedCode.Text + txtCode.Text);
                                var q4 = db.MsInfoOthers.FirstOrDefault(s => s.MsShobeId == RowId);
                                if (q4 != null)
                                {

                                    q4.MsShobeId = RowId;
                                    q4.MsCode = _code;
                                    q4.MsName = txtName.Text;
                                    q4.NoeShakhs = radioButton1.Checked ? "حقیقی" : "حقوقی";
                                    q4.NoeFaaliat = txtNoeFaaliat.Text;
                                    q4.Adress = txtAdress.Text;
                                    q4.CodePosti = txtCodePosti.Text;
                                    q4.SandoghPosti = txtSandoghPosti.Text;
                                    q4.ShomarePlak = txtShomarePlak.Text;
                                    q4.ShomareSabt = txtShomareSabt.Text;
                                    q4.CodeMelli = txtCodeMelli.Text;
                                    q4.ShenaseMelli = txtShenaseMelli.Text;
                                    q4.CodeSenfee = txtCodeSenfee.Text;
                                    q4.CodeEghtesadi = txtCodeEghtesadi.Text;
                                    q4.Tell1 = txtTell1.Text;
                                    q4.Tell2 = txtTell2.Text;
                                    q4.TellFax1 = txtTellFax1.Text;
                                    q4.TellFax2 = txtTellFax2.Text;
                                    q4.Mobile1 = txtMobile1.Text;
                                    q4.Mobile2 = txtMobile2.Text;
                                    q4.Email1 = txtEmail1.Text;
                                    q4.Email2 = txtEmail2.Text;
                                    q4.Site = txtSite.Text;
                                    q4.WebLog = txtWebLog.Text;
                                    q4.ShabakeEjtemaee1 = txtShabakeEjtemaee1.Text;
                                    q4.ShabakeEjtemaee2 = txtShabakeEjtemaee2.Text;
                                    q4.ShParvandeMaliati = txtShParvandeMaliati.Text;
                                    q4.ShBimeKargah = txtShBimeKargah.Text;
                                    db.MsInfoOthers.Remove(q4);
                                }
                                db.SaveChanges();

                                Fm.btnDisplyActiveList_ItemClick(null, null);
                                XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                this.Close();
                                Fm.gridView1.FocusedRowHandle = HelpClass1.EditRowIndex - 1;
                            }
                            else
                                XtraMessageBox.Show("رکورد جاری در بانک اطلاعاتی موجود نیست", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                        catch (DbUpdateException)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد \n حذف رکورد جاری مقدور نیست \n" +
                                " جهت حذف رکورد جاری در ابتدا بایستی زیر مجموعه های رکورد جاری (در لیست دوره ها) حذف گردد" +
                                "", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                        catch (Exception ex)
                        {
                            XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                        }
                    }
                }
            }

        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            this.Close();

        }

        private bool TextEditValidation()
        {
            ///////////////// اعتبار سنجی کد ////////////////////////////////////
            if (string.IsNullOrEmpty(txtCode.Text))
            {
                XtraMessageBox.Show("لطفا کد را وارد کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else if (Convert.ToInt32(txtCode.Text) == 0)
            {
                XtraMessageBox.Show("کد وارده باید عددی بزرگتر از صفر باشد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                if (this.Text == "ایجاد رکورد جدید")
                {
                    btnNewCode_Click(null, null);
                }
                else
                {
                    txtCode.Text = CodeBeforeEdit;
                }

                return false;
            }
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        if (this.Text == "ایجاد رکورد جدید")
                        {
                            if (db.MsShobes.Any())
                            {
                                int _code = Convert.ToInt32(txtVahedCode.Text + txtCode.Text);
                                var q1 = db.MsShobes.Where(p => p.ShobeCode == _code);
                                if (q1.Any())
                                {
                                    XtraMessageBox.Show("این کد قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                    btnNewCode_Click(null, null);
                                    return false;
                                }
                            }
                        }
                        else if (this.Text == "ویرایش رکورد جاری")
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            int _code = Convert.ToInt32(txtVahedCode.Text + txtCode.Text);
                            var q1 = db.MsShobes.Where(p => p.MsShobeId != RowId && p.ShobeCode == _code);
                            if (q1.Any())
                            {
                                XtraMessageBox.Show("این کد قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                txtCode.Text = CodeBeforeEdit;
                                return false;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }
            ////////////////// اعتبار سنجی تکس باکس و کمبوباکس ها////////////

            if (string.IsNullOrEmpty(txtName.Text) || txtName.Text == "0" || string.IsNullOrEmpty(cmbMajmoehaList.EditValue.ToString()) || string.IsNullOrEmpty(cmbVahedhaList.EditValue.ToString()))
            {
                XtraMessageBox.Show("لطفاً اطلاعات را کامل وارد کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return false;
            }
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        if (this.Text == "ایجاد رکورد جدید")
                        {
                            if (db.MsShobes.Any())
                            {
                                var q1 = db.MsShobes.Where(p => p.MsVahedId == _VahedId && p.ShobeName == txtName.Text);
                                if (q1.Any())
                                {
                                    XtraMessageBox.Show("این شعبه قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                    return false;
                                }
                            }
                        }
                        else if (this.Text == "ویرایش رکورد جاری")
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q1 = db.MsShobes.Where(p => p.MsVahedId == _VahedId && p.MsShobeId != RowId && p.ShobeName == txtName.Text);
                            if (q1.Any())
                            {
                                XtraMessageBox.Show("این شعبه قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                //txtName.Text = nameBeforeEdit;
                                return false;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }

            return true;
        }

        private void cmbListMajmoeha_EditValueChanged(object sender, EventArgs e)
        {
            FillcmbVahedhaList();
        }

        int _VahedId = 0;
        private void cmbVahedhaList_EditValueChanged(object sender, EventArgs e)
        {
            _VahedId = Convert.ToInt32(cmbVahedhaList.EditValue);
            FilltxtVahedCode();
            FillchkcmbPermissiveUsers();
        }

        private void cmbMajmoehaList_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                cmbMajmoehaList.ShowPopup();
            }
            else
            {
                cmbMajmoehaList.ClosePopup();
            }

        }

        private void cmbVahedhaList_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                cmbVahedhaList.ShowPopup();
            }
            else
            {
                cmbVahedhaList.ClosePopup();
            }

        }

        private void chkcmbPermissiveUsers_Enter(object sender, EventArgs e)
        {
            if (this.Text == "ایجاد رکورد جدید")
            {
                chkcmbPermissiveUsers.ShowPopup();
            }
            else
            {
                chkcmbPermissiveUsers.ClosePopup();
            }

        }

        private void chkSpecificationOther_CheckedChanged(object sender, EventArgs e)
        {
            this.Height = chkSpecificationOther.Checked ? 670 : 336;

        }

        private void radioButton1_CheckedChanged(object sender, EventArgs e)
        {
            if (radioButton1.Checked)
            {
                txtShomarePlak.Enabled = true;
                txtCodeMelli.Enabled = true;
                txtCodeSenfee.Enabled = true;
                txtShomareSabt.Enabled = false;
                txtShenaseMelli.Enabled = false;
                txtCodeEghtesadi.Enabled = false;
            }
            else
            {
                txtShomarePlak.Enabled = false;
                txtCodeMelli.Enabled = false;
                txtCodeSenfee.Enabled = false;
                txtShomareSabt.Enabled = true;
                txtShenaseMelli.Enabled = true;
                txtCodeEghtesadi.Enabled = true;

            }

        }

        private void FrmShoabatCed_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F2)
            {
                btnCreateClose_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F3)
            {
                btnCreateNext_Click(sender, null);
            }
            else if (e.KeyCode == Keys.Escape)
            {
                btnClose_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F7)
            {
                btnNewCode_Click(sender, null);
            }

        }

        private void chkEditCode_CheckedChanged(object sender, EventArgs e)
        {
            txtCode.ReadOnly = chkEditCode.Checked ? false : true;

        }
    }

}
