using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using DBHesabdari_PG;
using HelpClassLibrary;
using System.Data.Entity.Infrastructure;
using DBHesabdari_PG.Models.EP.CodingAnbar;
using DBHesabdari_PG.Models.EP.CodingHesabdari;

namespace EtelaatePaye.CodingAnbar
{
    public partial class FrmListAnbarha : DevExpress.XtraEditors.XtraForm
    {
        public FrmListAnbarha()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            DBHesabdari_PG.MyContext dbContext = new DBHesabdari_PG.MyContext();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.EpAllHesabTafsilis.Load();
            // This line of code is generated by Data Source Configuration Wizard
            cmbHesabTafsili1.Properties.DataSource = dbContext.EpAllHesabTafsilis.Local.ToBindingList();
        }

        public EnumCED En;
        int _SalId = 0;
        public void FillDataGrid()
        {
            using (var db = new MyContext())
            {
                try
                {
                    btnDelete.Enabled = btnEdit.Enabled = btnLast.Enabled = btnNext.Enabled = btnPreview.Enabled = btnFirst.Enabled = false;
                    _SalId = Convert.ToInt32(lblSalId.Text);
                    var q1 = db.EpListAnbarhas.Where(s => s.SalId == _SalId).OrderBy(s => s.Code).ToList();
                    if (lblUserId.Text == "1")
                        epListAnbarhasBindingSource.DataSource = q1.Count > 0 ? q1 : null;
                    //else
                    //{
                    //    int _UserId = Convert.ToInt32(lblUserId.Text);
                    //    var q2 = dataContext.RmsUserBallCodingHesabdaris.Where(s => s.UserId == _UserId && s.HesabMoinId > 0 ).Select(s => s.HesabMoinId).ToList();

                    //    if (q1.Count > 0)
                    //    {
                    //        if (q2.Count > 0)
                    //        {
                    //            q2.ForEach(item2 =>
                    //            {
                    //                q1.Remove(dataContext.EpHesabTafsiliSandoghs.FirstOrDefault(s => s.Id == item2));
                    //            });
                    //            epHesabTafsiliSandoghsBindingSource.DataSource = q1;
                    //        }
                    //        else
                    //        {
                    //            epHesabTafsiliSandoghsBindingSource.DataSource = q1;
                    //        }
                    //    }
                    //    else
                    //        epHesabTafsiliSandoghsBindingSource.DataSource = null;
                    //}
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }


        private void btnNewCode_Click(object sender, EventArgs e)
        {
            using (var db = new MyContext())
            {
                try
                {
                    var q = db.EpListAnbarhas.Select(s => s);
                    if (q.Any())
                    {
                        var MaximumCod = q.Max(s => s.Code);
                        if (MaximumCod.ToString() != _CodeAnbarMaxCode)
                        {
                            txtCode.Text = (MaximumCod + 1).ToString();
                        }
                        else
                        {
                            XtraMessageBox.Show("اعمال محدودیت تعریف" + _CodeAnbarMaxCode + "حساب انبار ..." + "\n" + "توجه : نمیتوان بیشتر از" + _CodeAnbarMaxCode + "حساب انبار تعریف کرد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                            chkEditCode.Checked = true;
                        }

                    }
                    else
                    {
                        txtCode.Text = "001";
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

        string CodeBeforeEdit = "";
        string NameBeforeEdit = "";
        bool IsActiveBeforeEdit = true;
        int _CodeAnbarCarakter = 0;
        string _CodeAnbarMinCode = "";
        string _CodeAnbarMaxCode = "";

        private void FrmListAnbarha_Load(object sender, EventArgs e)
        {
            _SalId = Convert.ToInt32(lblSalId.Text);
            FillDataGrid();
            btnDelete.Enabled = btnEdit.Enabled = btnLast.Enabled = btnNext.Enabled = btnPreview.Enabled = btnFirst.Enabled = false;
            using (var db = new MyContext())
            {
                try
                {
                    var q = db.EpTanzimatAnbarVKalas.FirstOrDefault(s => s.SalId == _SalId);
                    if (q != null)
                    {
                        _CodeAnbarCarakter = q.CodeAnbarCarakter;

                        _CodeAnbarMinCode = q.CodeAnbarMinCode;
                        _CodeAnbarMaxCode = q.CodeAnbarMaxCode;
                        txtCode.Properties.Mask.MaskType = DevExpress.XtraEditors.Mask.MaskType.Numeric; ;
                        txtCode.Properties.Mask.EditMask = "000";
                        txtCode.Properties.MaxLength = _CodeAnbarCarakter;
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
            En = EnumCED.None;
            xtraTabControl1.SelectedTabPageIndex = 1;
            xtraTabControl1.SelectedTabPageIndex = 0;

            btnCreate.Focus();

            //if (lblUserId.Text == "1")
            //{
            //    chkIsActive.Visible = true;
            //    labelControl6.Visible = true;
            //}
            //labelControl1.Text = "کد صندوق";
            //labelControl2.Text = "نام صندوق";
            //using (var db = new MyContext())
            //{
            //    try
            //    {
            //        int _UserId = Convert.ToInt32(lblUserId.Text);
            //        var q1 = db.RmsUserBmsAccessLevelMenus.Where(s => s.MsUserId == _UserId).ToList();
            //        if (q1.Count() > 0)
            //        {
            //            //btnCreate.Visibility = q1.Any(s => s.MsAccessLevelMenuId == 55010201) ? BarItemVisibility.Never : BarItemVisibility.Always;
            //            //btnEdit.Visibility = q1.Any(s => s.MsAccessLevelMenuId == 55010202) ? BarItemVisibility.Never : BarItemVisibility.Always;
            //            //btnDelete.Visibility = q1.Any(s => s.MsAccessLevelMenuId == 55010203) ? BarItemVisibility.Never : BarItemVisibility.Always;
            //        }
            //    }
            //    catch (Exception ex)
            //    {
            //        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
            //            "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
            //    }
            //}

        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            if (btnClose.Enabled)
            {
                this.Close();

            }        }

        private bool TextEditValidation()
        {
            ///////////////// اعتبار سنجی کد ////////////////////////////////////
            if (string.IsNullOrEmpty(txtCode.Text))
            {
                XtraMessageBox.Show("لطفا کد حساب را وارد کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                txtCode.Focus();
                return false;
            }
            else if (Convert.ToInt32(txtCode.Text) < Convert.ToInt32(_CodeAnbarMinCode) || Convert.ToInt32(txtCode.Text) > Convert.ToInt32(_CodeAnbarMaxCode))
            {
                XtraMessageBox.Show("کد وارده بایستی عددی از " + _CodeAnbarMinCode + " تا " + _CodeAnbarMaxCode + " باشد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                txtCode.Focus();
                return false;
            }
            else if (cmbNoeAnbar.SelectedIndex == -1)
            {
                XtraMessageBox.Show("لطفا نوع انبار را مشخص کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                cmbNoeAnbar.Focus();
                return false;
            }
            else if (Convert.ToInt32(cmbHesabMoin.EditValue) == 0)
            {
                XtraMessageBox.Show("لطفا حساب معین را مشخص کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                cmbHesabMoin.Focus();
                return false;
            }
            //else if (Convert.ToInt32(cmbHesabTafsili1.EditValue) == 0)
            //{
            //    XtraMessageBox.Show("لطفا حساب تفصیلی را مشخص کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            //    cmbHesabTafsili1.Focus();
            //    return false;
            //}
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        int _Code = Convert.ToInt32(txtCode.Text);
                        _SalId = Convert.ToInt32(lblSalId.Text);
                        if (En == EnumCED.Create)
                        {
                            var q1 = db.EpListAnbarhas.FirstOrDefault(s => s.SalId == _SalId && s.Code == _Code);
                            if (q1 != null)
                            {
                                XtraMessageBox.Show("این کد قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                btnNewCode_Click(null, null);
                                return false;
                            }
                        }
                        else if (En == EnumCED.Edit)
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q1 = db.EpListAnbarhas.FirstOrDefault(s => s.SalId == _SalId && s.Id != RowId && s.Code == _Code);
                            if (q1 != null)
                            {
                                XtraMessageBox.Show("این کد قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                txtCode.Text = CodeBeforeEdit;
                                return false;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
            ////////////////// اعتبار سنجی تکس باکس و کمبوباکس ها////////////

            if (string.IsNullOrEmpty(txtName.Text) || txtName.Text == "0")
            {
                XtraMessageBox.Show("لطفاً نام انبار را وارد کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                txtName.Focus();
                return false;
            }
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        if (En == EnumCED.Create)
                        {
                            var q1 = db.EpListAnbarhas.FirstOrDefault(s => s.SalId == _SalId && s.Name == txtName.Text);
                            if (q1 != null)
                            {
                                XtraMessageBox.Show("این نام قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                txtName.Focus();
                                return false;
                            }
                        }
                        else if (En == EnumCED.Edit)
                        {
                            int RowId = Convert.ToInt32(txtId.Text);
                            var q1 = db.EpListAnbarhas.FirstOrDefault(s => s.SalId == _SalId && s.Id != RowId && s.Name == txtName.Text);
                            if (q1 != null)
                            {
                                XtraMessageBox.Show("این نام قبلاً تعریف شده است", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                                txtName.Focus();
                                //txtName.Text = nameBeforeEdit;
                                return false;
                            }
                        }
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }
            }
            return true;
        }

        private void FrmListAnbarha_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.F2)
            {
                btnCreate_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F3)
            {
                btnDelete_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F4)
            {
                btnEdit_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F5)
            {
                btnSave_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F6)
            {
                btnSaveNext_Click(sender, null);
            }
            //else if (e.KeyCode == Keys.F7)
            //{
            //    btnCancel_Click(sender, null);
            //}
            //else if (e.KeyCode == Keys.F8)
            //{
            //    btnDisplyList_Click(sender, null);
            //}
            else if (e.KeyCode == Keys.F10)
            {
                btnPrintPreview_Click(sender, null);
            }
            else if (e.KeyCode == Keys.F12)
            {
                btnClose_Click(sender, null);
            }
        }

        private void chkEditCode_CheckedChanged(object sender, EventArgs e)
        {
            btnNewCode.Enabled = txtCode.Enabled = chkEditCode.Checked ? true : false;
        }

        private void btnLast_Click(object sender, EventArgs e)
        {
            HelpClass1.MoveLast(gridView1);
        }

        private void btnNext_Click(object sender, EventArgs e)
        {
            HelpClass1.MoveNext(gridView1);

        }

        private void btnPreview_Click(object sender, EventArgs e)
        {
            HelpClass1.MovePrev(gridView1);

        }

        private void btnFirst_Click(object sender, EventArgs e)
        {
            HelpClass1.MoveFirst(gridView1);
        }

        private void btnPrintPreview_Click(object sender, EventArgs e)
        {
            if (btnPrintPreview.Visible)
                HelpClass1.PrintPreview(gridControl1, gridView1);
        }

        public void btnDisplyList_Click(object sender, EventArgs e)
        {
            FillDataGrid();
        }

        private void gridView1_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == 13)
            {
                btnEdit_Click(null, null);
            }

        }

        private void gridView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            HelpClass1.SetNumberRowsColumnUnboundGirdView(sender, e);
        }

        private void btnCreate_Click(object sender, EventArgs e)
        {
            if (btnCreate.Enabled)
            {
                En = EnumCED.Create;
                gridControl1.Enabled = false;
                FillCmbHesabMoin();
                HelpClass1.InActiveButtons(panelControl2);
                HelpClass1.ClearControls(panelControl1_1);
                HelpClass1.ClearControls(panelControl1_2);
                HelpClass1.ActiveControls(panelControl1_1);
                HelpClass1.ActiveControls(panelControl1_2);
                //cmbListGroupTafsili.EditValue = 1;
                //txtCodeGroupTafsili.Text = "10";
                xtraTabControl1.SelectedTabPageIndex = 0;
                btnNewCode_Click(null, null);
                // cmbListGroupTafsili.EditValue = 13;
                chkIsActive.Checked = true;
                txtName.Focus();
            }
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            if (btnDelete.Enabled)
            {
                if (gridView1.RowCount > 0)
                {
                    if (XtraMessageBox.Show("آیا انبار فوق حذف گردد؟", "پیغام حذف", MessageBoxButtons.YesNo, MessageBoxIcon.Information) == DialogResult.Yes)
                    {
                        IsActiveBeforeEdit = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("IsActive"));
                        EditRowIndex = gridView1.FocusedRowHandle;
                        using (var db = new MyContext())
                        {
                            try
                            {
                                int RowId = Convert.ToInt32(gridView1.GetFocusedRowCellValue("Id").ToString());
                                var q = db.EpListAnbarhas.FirstOrDefault(s => s.SalId == _SalId && s.Id == RowId);
                                if (q != null)
                                {
                                    db.EpListAnbarhas.Remove(q);
                                    /////////////////////////////////////////////////////////////////////////////
                                    db.SaveChanges();

                                    btnDisplyList_Click(null, null);
                                    // XtraMessageBox.Show("عملیات حذف با موفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                    if (gridView1.RowCount > 0)
                                        gridView1.FocusedRowHandle = EditRowIndex - 1;
                                    HelpClass1.ClearControls(panelControl1_1);
                                    HelpClass1.ClearControls(panelControl1_2);
                                }
                                else
                                    XtraMessageBox.Show("رکورد جاری در بانک اطلاعاتی موجود نیست", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }
                            catch (DbUpdateException)
                            {
                                XtraMessageBox.Show("حذف این حساب مقدور نیست \n" +
                                    " زیرا با حساب فوق سند صادر گردیده", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }
                            catch (Exception ex)
                            {
                                XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }
                        }
                    }
                }

            }
        }

        public int EditRowIndex = 0;
        private void btnEdit_Click(object sender, EventArgs e)
        {
            if (btnEdit.Enabled)
            {
                if (gridView1.RowCount > 0)
                {
                    gridControl1.Enabled = false;
                    EditRowIndex = gridView1.FocusedRowHandle;
                    En = EnumCED.Edit;
                    HelpClass1.InActiveButtons(panelControl2);
                    HelpClass1.ActiveControls(panelControl1_1);
                    HelpClass1.ActiveControls(panelControl1_2);

                    gridView1_RowCellClick(null, null);
                    ////cmbListGroupTafsili.EditValue = 13;
                    //txtId.Text = gridView1.GetFocusedRowCellValue("Id").ToString();
                    ////txtCodeGroupTafsili.Text = gridView1.GetFocusedRowCellValue("Code").ToString().Substring(0, 2);
                    //txtCode.Text = gridView1.GetFocusedRowCellValue("Code").ToString();
                    //txtName.Text = gridView1.GetFocusedRowCellValue("Name").ToString();
                    //cmbNoeAnbar.SelectedIndex = Convert.ToInt32(gridView1.GetFocusedRowCellValue("IndexNoeAnbar").ToString());
                    //chkMojavezMojodiManfi.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("MojavezMojodiManfi"));
                    //chkIsActive.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("IsActive"));
                    //txtSharhHesab.Text = gridView1.GetFocusedRowCellValue("SharhHesab").ToString();

                    CodeBeforeEdit = txtCode.Text;
                    NameBeforeEdit = txtName.Text;
                    IsActiveBeforeEdit = chkIsActive.Checked;
                    //if (txtCode.Text == "99999")
                    //    btnNewCode.Enabled = false;
                    cmbHesabTafsili1.ShowPopup();
                    cmbHesabTafsili1.ClosePopup();
                    cmbHesabTafsili2.ShowPopup();
                    cmbHesabTafsili2.ClosePopup();
                    cmbHesabTafsili3.ShowPopup();
                    cmbHesabTafsili3.ClosePopup() ;
                    txtName.Focus();
                }

            }
        }

        private void btnSave_Click(object sender, EventArgs e)
        {
            if (btnSave.Enabled)
            {
                if (TextEditValidation())
                {
                    if (En == EnumCED.Create)
                    {
                        using (var db = new MyContext())
                        {
                            try
                            {
                                EpListAnbarha obj = new EpListAnbarha();
                                obj.SalId = Convert.ToInt32(lblSalId.Text);
                                obj.Code = Convert.ToInt32(txtCode.Text);
                                obj.Name = txtName.Text;
                                obj.IndexNoeAnbar = cmbNoeAnbar.SelectedIndex;
                                obj.NoeAnbar = cmbNoeAnbar.Text;
                                obj.MojavezMojodiManfi = chkMojavezMojodiManfi.Checked;
                                obj.IsActive = chkIsActive.Checked;
                                obj.SharhHesab = txtSharhHesab.Text;
                                obj.MoinId = Convert.ToInt32(cmbHesabMoin.EditValue);
                                var qq = db.EpAllHesabTafsilis.Where(s => s.SalId == _SalId && s.EpAllGroupTafsili1.TabaghehGroupName == "سایر");
                                obj.TafsiliId1 = Convert.ToInt32(cmbHesabTafsili1.EditValue)>0  ? Convert.ToInt32(cmbHesabTafsili1.EditValue) : qq.FirstOrDefault(s=>s.LevelNamber==1&& s.Name=="سایر 1").Id;
                                obj.TafsiliId2 = Convert.ToInt32(cmbHesabTafsili2.EditValue)>0 ? Convert.ToInt32(cmbHesabTafsili2.EditValue) : qq.FirstOrDefault(s => s.LevelNamber == 2 && s.Name == "سایر 2").Id;
                                obj.TafsiliId3 = Convert.ToInt32(cmbHesabTafsili3.EditValue)>0 ? Convert.ToInt32(cmbHesabTafsili3.EditValue) : qq.FirstOrDefault(s => s.LevelNamber == 3 && s.Name == "سایر 3").Id;

                                db.EpListAnbarhas.Add(obj);
                                db.SaveChanges();
                                /////////////////////////////////////////////////////////////////////////////////////
                                //int _Code = Convert.ToInt32(txtCodeGroupTafsiliSandogh.Text + txtCode.Text);
                                //var q = db.EpHesabTafsiliSandoghs.FirstOrDefault(s => s.Code == _Code);
                                //////////////////////////////////////// اضافه کردن حساب کل به کلاس سطح دسترسی کدینگ حسابداری ////////////////////
                                //EpAllCodingHesabdari n1 = new EpAllCodingHesabdari();
                                //n1.KeyId = _Code;
                                //n1.ParentId = Convert.ToInt32(txtGroupCode.Text);
                                //n1.LevelName = txtName.Text;
                                //n1.HesabGroupId = q.GroupId;
                                //n1.HesabColId = q.Id;
                                //n1.IsActive = chkIsActive.Checked;
                                //db.EpAllCodingHesabdaris.Add(n1);
                                ///////////////////////////////////////////////////////////////////////////////////////
                                //db.SaveChanges();
                                btnCancel_Click(null, null);
                                btnDisplyList_Click(null, null);
                                // XtraMessageBox.Show("عملیات ایجاد با موفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                btnLast_Click(null, null);
                                En = EnumCED.Save;
                            }
                            catch (Exception ex)
                            {
                                XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }
                        }
                    }
                    else if (En == EnumCED.Edit)
                    {
                        using (var db = new MyContext())
                        {
                            try
                            {
                                int RowId = Convert.ToInt32(txtId.Text);
                                var q = db.EpListAnbarhas.FirstOrDefault(s => s.Id == RowId);
                                if (q != null)
                                {
                                    q.Code = Convert.ToInt32(txtCode.Text);
                                    q.Name = txtName.Text;
                                    q.IndexNoeAnbar = cmbNoeAnbar.SelectedIndex;
                                    q.NoeAnbar = cmbNoeAnbar.Text;
                                    q.MojavezMojodiManfi = chkMojavezMojodiManfi.Checked;
                                    q.IsActive = chkIsActive.Checked;
                                    q.SharhHesab = txtSharhHesab.Text;
                                    q.MoinId = Convert.ToInt32(cmbHesabMoin.EditValue);
                                    //q.TafsiliId1 = Convert.ToInt32(cmbHesabTafsili1.EditValue);
                                    //q.TafsiliId2 = Convert.ToInt32(cmbHesabTafsili2.EditValue);
                                    //q.TafsiliId3 = Convert.ToInt32(cmbHesabTafsili3.EditValue);
                                    var qq = db.EpAllHesabTafsilis.Where(s => s.SalId == _SalId && s.EpAllGroupTafsili1.TabaghehGroupName == "سایر");
                                    q.TafsiliId1 = Convert.ToInt32(cmbHesabTafsili1.EditValue) > 0 ? Convert.ToInt32(cmbHesabTafsili1.EditValue) : qq.FirstOrDefault(s => s.LevelNamber == 1 && s.Name == "سایر 1").Id;
                                    q.TafsiliId2 = Convert.ToInt32(cmbHesabTafsili2.EditValue) > 0 ? Convert.ToInt32(cmbHesabTafsili2.EditValue) : qq.FirstOrDefault(s => s.LevelNamber == 2 && s.Name == "سایر 2").Id;
                                    q.TafsiliId3 = Convert.ToInt32(cmbHesabTafsili3.EditValue) > 0 ? Convert.ToInt32(cmbHesabTafsili3.EditValue) : qq.FirstOrDefault(s => s.LevelNamber == 3 && s.Name == "سایر 3").Id;

                                    db.SaveChanges();
                                    btnCancel_Click(null, null);
                                    btnDisplyList_Click(null, null);
                                    // XtraMessageBox.Show("عملیات ویرایش با موفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information); ;
                                    if (gridView1.RowCount > 0)
                                        gridView1.FocusedRowHandle = EditRowIndex;
                                    En = EnumCED.Save;
                                }
                                else
                                    XtraMessageBox.Show("رکورد جاری در بانک اطلاعاتی موجود نیست", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }
                            catch (Exception ex)
                            {
                                XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message, "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                            }
                        }
                    }
                }

            }
        }

        private void btnSaveNext_Click(object sender, EventArgs e)
        {
            if (btnSaveNext.Enabled)
            {
                btnSave_Click(null, null);
                if (En == EnumCED.Save)
                    btnCreate_Click(null, null);
            }
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
                gridControl1.Enabled = true;
                En = EnumCED.Cancel;
                HelpClass1.ActiveButtons(panelControl2);
                HelpClass1.ClearControls(panelControl1_1);
                HelpClass1.ClearControls(panelControl1_2);
                HelpClass1.InActiveControls(panelControl1_1);
                HelpClass1.InActiveControls(panelControl1_2);
                //cmbHesabMoin.EditValue = cmbHesabTafsili1.EditValue = cmbHesabTafsili2.EditValue = cmbHesabTafsili3.EditValue = null;
                //epHesabMoin1sBindingSource.DataSource = epHesabTafsiliAnbarhasBindingSource.DataSource = null;
                btnCreate.Focus();
        }

        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            try
            {
                if (gridView1.RowCount > 0)
                {

                    txtId.Text = gridView1.GetFocusedRowCellValue("Id").ToString();
                    //txtCodeGroupTafsili.Text = gridView1.GetFocusedRowCellValue("Code").ToString().Substring(0, 2);
                    txtCode.Text = gridView1.GetFocusedRowCellValue("Code").ToString();
                    txtName.Text = gridView1.GetFocusedRowCellValue("Name").ToString();
                    cmbNoeAnbar.SelectedIndex = Convert.ToInt32(gridView1.GetFocusedRowCellValue("IndexNoeAnbar").ToString());
                    chkMojavezMojodiManfi.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("MojavezMojodiManfi"));
                    chkIsActive.Checked = Convert.ToBoolean(gridView1.GetFocusedRowCellValue("IsActive"));
                    txtSharhHesab.Text = gridView1.GetFocusedRowCellValue("SharhHesab").ToString();
                    FillCmbHesabMoin();
                    cmbHesabMoin.EditValue = Convert.ToInt32(gridView1.GetFocusedRowCellValue("MoinId").ToString());
                    // cmbHesabTafsili1.EditValue = Convert.ToInt32(gridView1.GetFocusedRowCellValue("TafsiliId").ToString());
                    int s1 = Convert.ToInt32(gridView1.GetFocusedRowCellValue("TafsiliId1").ToString());
                    int s2 = Convert.ToInt32(gridView1.GetFocusedRowCellValue("TafsiliId2").ToString());
                    int s3 = Convert.ToInt32(gridView1.GetFocusedRowCellValue("TafsiliId3").ToString());
                    cmbHesabTafsili1.Text = new MyContext().EpAllHesabTafsilis.FirstOrDefault(s => s.Id == s1).Name;
                    cmbHesabTafsili2.Text = new MyContext().EpAllHesabTafsilis.FirstOrDefault(s => s.Id == s2).Name;
                    cmbHesabTafsili3.Text = new MyContext().EpAllHesabTafsilis.FirstOrDefault(s => s.Id == s3).Name;
                    // int s2 = Convert.ToInt32(gridView1.GetFocusedRowCellValue("TafsiliId").ToString());
                    // int s = Convert.ToInt32(cmbHesabTafsili1.EditValue);
                    if (En != EnumCED.Edit)
                        btnDelete.Enabled = btnEdit.Enabled = btnLast.Enabled = btnNext.Enabled = btnPreview.Enabled = btnFirst.Enabled = true;
                }
            }
            catch (Exception)
            {
            }
        }

        private void gridView1_KeyDown(object sender, KeyEventArgs e)
        {
            gridView1_RowCellClick(null, null);
        }

        private void gridView1_KeyUp(object sender, KeyEventArgs e)
        {
            gridView1_RowCellClick(null, null);

        }

        private void cmbNoeAnbar_Enter(object sender, EventArgs e)
        {
            if (En == EnumCED.Create)
            {
                cmbNoeAnbar.ShowPopup();
            }
        }

        private void gridView1_RowCellStyle(object sender, DevExpress.XtraGrid.Views.Grid.RowCellStyleEventArgs e)
        {
            HelpClass1.gridView_RowCellStyle(sender, e);
        }

        private void cmbHesabMoin_CustomDrawCell(object sender, DevExpress.XtraEditors.Popup.LookUpCustomDrawCellArgs e)
        {
            HelpClass1.LookupEdit_CustomDrawCell(sender, e);

        }

        private void cmbHesabTafsili_CustomDrawCell(object sender, DevExpress.XtraEditors.Popup.LookUpCustomDrawCellArgs e)
        {
            HelpClass1.LookupEdit_CustomDrawCell(sender, e);

        }

        private void cmbHesabMoin_Enter(object sender, EventArgs e)
        {
            if (En == EnumCED.Create)
            {
                cmbHesabMoin.ShowPopup();
            }
            memoEdit1.Text = "در این قسمت با توجه به نوع انبار ، حساب معین موجودی مواد ، کالا و یا محصول انتخاب شود";

        }


        public void FillCmbHesabMoin()
        {
            using (var db = new MyContext())
            {
                try
                {
                    _SalId = Convert.ToInt32(lblSalId.Text);
                    var q = db.EpHesabMoin1s.Where(s => s.SalId == _SalId).OrderBy(s => s.Code).ToList();
                    epHesabMoin1sBindingSource.DataSource = q.Count > 0 ? q : null;
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
        List<EpAllHesabTafsili> list;
        //List<EpAllHesabTafsili_HesabMovaghat> list1;
        public void FillCmbHesabTafsili()
        {
            using (var db = new MyContext())
            {
                try
                {
                    _SalId = Convert.ToInt32(lblSalId.Text);
                    int _HesabMoinId = Convert.ToInt32(cmbHesabMoin.EditValue);
                    // list = null;
                    list = new List<EpAllHesabTafsili>();

                    var q1 = db.REpAllCodingHesabdariBEpAllGroupTafsilis.Where(s => s.AllCodingHesabdariId == _HesabMoinId && s.SalId == _SalId).Select(s => s.AllGroupTafsiliId).ToList();
                    if (q1.Count > 0)
                    {
                        foreach (var item in q1)
                        {
                            var q = db.EpAllHesabTafsilis.Where(s => s.SalId == _SalId && s.GroupTafsiliId == item).OrderBy(s => s.Code).ToList();
                            list.AddRange(q);
                        }
                        #region MyRegion
                        // //db.EpAllHesabTafsilis.AddRange(list);
                        //// list1 = null;
                        // list1 = new List<EpAllHesabTafsili_HesabMovaghat>();
                        // foreach (var item in list)
                        // {
                        //     EpAllHesabTafsili_HesabMovaghat obj = new EpAllHesabTafsili_HesabMovaghat();
                        //     obj.Id = item.Id;
                        //     obj.SalId = item.SalId;
                        //     obj.LevelNamber = item.LevelNamber;
                        //     obj.Code = item.Code;
                        //     obj.Name = item.Name;
                        //     obj.GroupTafsiliId = item.GroupTafsiliId;
                        //     obj.MoinId = _HesabMoinId;
                        //     obj.IsActive = item.IsActive;
                        //     obj.IsDefault = item.IsDefault;
                        //     obj.SharhHesab = item.SharhHesab;
                        //     list1.Add(obj);
                        // }
                        // db.EpAllHesabTafsili_HesabMovaghats.AddRange(list1);

                        // //BindingSource bs = new BindingSource();
                        // //bs.DataSource = list;
                        // //BindingList<EpAllHesabTafsili> ok = new BindingList<EpAllHesabTafsili>(list);
                        // db.EpAllHesabTafsili_HesabMovaghats.Load();
                        // epHesabTafsiliAnbarhasBindingSource.DataSource = db.EpAllHesabTafsili_HesabMovaghats.Local.ToBindingList(); 
                        #endregion
                        cmbHesabTafsili1.Properties.DataSource = list.Where(s => s.LevelNamber == 1).OrderBy(s => s.Code);
                        cmbHesabTafsili2.Properties.DataSource = list.Where(s => s.LevelNamber == 2).OrderBy(s => s.Code);
                        cmbHesabTafsili3.Properties.DataSource = list.Where(s => s.LevelNamber == 3).OrderBy(s => s.Code);
                    }
                    else
                    {
                        cmbHesabTafsili1.Properties.DataSource = null;
                        cmbHesabTafsili2.Properties.DataSource = null;
                        cmbHesabTafsili3.Properties.DataSource = null;

                    }

                    //if (_HesabMoinId == 14)
                    //{
                    //    cmbHesabTafsili.Properties.DataSource = db.EpAllHesabTafsilis.Where(s => s.GroupTafsiliId == 1 || s.GroupTafsiliId == 2).ToList();
                    //}
                    //else if (_HesabMoinId == 15)
                    //{
                    //    cmbHesabTafsili.Properties.DataSource = db.EpAllHesabTafsilis.Where(s => s.GroupTafsiliId == 3 || s.GroupTafsiliId == 4).ToList();
                    //}

                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }

        private void btnReloadHesabMoin_Click(object sender, EventArgs e)
        {
            FillCmbHesabMoin();
        }

        private void btnReloadHesabTafsili_Click(object sender, EventArgs e)
        {
            FillCmbHesabTafsili();
        }

        private void cmbHesabMoin_EditValueChanged(object sender, EventArgs e)
        {
            using (var db = new MyContext())
            {
                try
                {
                    FillCmbHesabTafsili();
                    _SalId = Convert.ToInt32(lblSalId.Text);
                    int _HesabMoinId = Convert.ToInt32(cmbHesabMoin.EditValue);
                    var q = db.EpHesabMoin1s.FirstOrDefault(s => s.SalId == _SalId && s.Id == _HesabMoinId);
                    if (q!=null)
                    {
                        switch (q.GroupLevelsId)
                        {
                            case 0:
                                {
                                    cmbHesabTafsili1.ReadOnly = cmbHesabTafsili2.ReadOnly = cmbHesabTafsili3.ReadOnly = true;
                                    break;
                                }
                            case 1:
                                {
                                    cmbHesabTafsili1.ReadOnly = false;
                                    cmbHesabTafsili2.ReadOnly = cmbHesabTafsili3.ReadOnly = true;
                                    break;
                                }
                            case 2:
                                {
                                    cmbHesabTafsili1.ReadOnly = cmbHesabTafsili2.ReadOnly = false;
                                    cmbHesabTafsili3.ReadOnly = true;
                                    break;
                                }
                            case 3:
                                {
                                    cmbHesabTafsili1.ReadOnly = cmbHesabTafsili2.ReadOnly = cmbHesabTafsili3.ReadOnly = false;
                                    break;
                                }
                            default:
                                break;
                        }

                    }                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }

        private void cmbHesabMoin_Click(object sender, EventArgs e)
        {
        }

        private void cmbHesabTafsili2_Click(object sender, EventArgs e)
        {
        }

        private void cmbHesabTafsili3_Click(object sender, EventArgs e)
        {

        }

        private void cmbHesabTafsili1_Enter(object sender, EventArgs e)
        {
            if (En == EnumCED.Create)
            {
                cmbHesabTafsili1.ShowPopup();
            }
            // memoEdit1.Text = "در قسمت اطلاعات پایه -> کدینگ حسابداری -> حسابهای تفصیلی سطح 1 -> در تب انبارها ، نام انبار مربوطه تعریف و در این قسمت انتخاب شود ضمناً ارتباط حساب معین با گروه تفصیلی انبارها در سطح یک داده شود";
            // memoEdit1.Text = "پیشنهاد : از قسمت اطلاعات پایه => کدینگ حسابداری => حسابهای تفصیلی سطح 1 => در تب انبارها ، انبار فعلی تعریف واز این قسمت انتخاب نمایید";
            memoEdit1.Text = "پیشنهاد : در صورتیکه میخواهید در حسابداری زیر گروه حساب معین انبار ، لیست کالاها بیاید  " +
                "اولین کالای تعریف شده دراین قسمت انتخاب شود در غیر اینصورت سایر 1 را در این قسمت انتخاب نمایید";

        }

        private void cmbHesabTafsili2_Enter(object sender, EventArgs e)
        {
            if (En == EnumCED.Create)
            {
                cmbHesabTafsili2.ShowPopup();
            }
            memoEdit1.Text = " پیشنهاد : در صورتیکه در حساب تفصیلی سطح 1  ، نام کالا انتخاب شده است و ضمناً واحد تجاری دارای چندین انبار می باشد  " +
                             "در قسمت اطلاعات پایه => کدینگ حسابداری => حسابهای تفصیلی سطح 2 => در تب انبارها ، " +
                             "نام انبار فعلی تعریف و در این قسمت انتخاب شود در غیر اینصورت گزینه سایر 2 را انتخاب نمایید";

            //memoEdit1.Text = "در قسمت اطلاعات پایه -> کدینگ حسابداری -> حسابهای تفصیلی سطح 1 -> " +
            //    "در تب انبارها ، نام انبار مربوطه تعریف و در این قسمت انتخاب شود ضمناً ارتباط حساب معین با گروه تفصیلی انبارها در سطح یک داده شود";
            //memoEdit1.Text = "پیشنهاد : در صورتیکه میخواهید در حسابداری ، زیر گروه حساب تفصیلی سطح 1 انبار ، لیست کالاها بیاید  " +
            //    "اولین کالای تعریف شده را دراین قسمت انتخاب نمایید در غیر اینصورت سایر 2 را در این قسمت انتخاب نمایید";

        }

        private void cmbHesabTafsili3_Enter(object sender, EventArgs e)
        {
            if (En == EnumCED.Create)
            {
                cmbHesabTafsili3.ShowPopup();
            }
            memoEdit1.Text = " پیشنهاد : در صورتیکه واحد تجاری بغیر از شعبه اصلی دارای شعبات وابسته و یا شعبات همگروه دیگری می باشد  " +
                             "در قسمت اطلاعات پایه => کدینگ حسابداری => حسابهای تفصیلی سطح 3 => در تب شعبات وابسته ،" +
                             " شعبه مورد نظر تعریف و در این قسمت انتخاب شود در غیر اینصورت گزینه سایر 3 را انتخاب نمایید";

        }

        private void cmbHesabTafsili2_CustomDrawCell(object sender, DevExpress.XtraEditors.Popup.LookUpCustomDrawCellArgs e)
        {
            HelpClass1.LookupEdit_CustomDrawCell(sender, e);

        }

        private void cmbHesabTafsili3_CustomDrawCell(object sender, DevExpress.XtraEditors.Popup.LookUpCustomDrawCellArgs e)
        {
            HelpClass1.LookupEdit_CustomDrawCell(sender, e);

        }

        private void chkIsActive_Leave(object sender, EventArgs e)
        {
            xtraTabControl1.SelectedTabPageIndex = 1;
            cmbHesabMoin.Focus();

        }

        private void cmbLookupEdit_CustomDrawRow(object sender, DevExpress.XtraEditors.Popup.LookUpCustomDrawRowArgs e)
        {
            HelpClass1._IsActiveRow = Convert.ToBoolean(e.GetCellValue(0));

        }
    }
}