/****************************** Ghost.github.io ******************************\
*	Module Name:	AnbarsName.cs
*	Project:		Hesabdari_TG_N1_V1
*	Copyright (C) 2018 Kamal Khayati, All rights reserved.
*	This software may be modified and distributed under the terms of the MIT license.  See LICENSE file for details.
*
*	Written by Kamal Khayati <Kamal1355@gmail.com>,  2018 / 12 / 17   02:11 ب.ظ
*	
***********************************************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;

namespace Hesabdari_TG_N1_V1.Forms.Base.AnbarKala
{
    public partial class FrmListAnbars : DevExpress.XtraEditors.XtraForm
    {
        public FrmListAnbars()
        {
            InitializeComponent();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            FrmSaveAnbars fm = new FrmSaveAnbars();
            fm.Text = "اضافه کردن انبار جدید";
            fm.btnSave.Text = "ذخیره";
            fm.ShowDialog();

        }

        // This event is generated by Data Source Configuration Wizard
        void entityInstantFeedbackSource1_GetQueryable(object sender, DevExpress.Data.Linq.GetQueryableEventArgs e)
        {

            // Instantiate a new DataContext
            Hesabdari_TG_N1_V1.Models.MyContext dataContext = new Hesabdari_TG_N1_V1.Models.MyContext();
            // Assign a queryable source to the EntityInstantFeedbackSource
            e.QueryableSource = dataContext.BaseAnbars;
            // Assign the DataContext to the Tag property,
            // to dispose of it in the DismissQueryable event handler
            e.Tag = dataContext;
        }

        // This event is generated by Data Source Configuration Wizard
        void entityInstantFeedbackSource1_DismissQueryable(object sender, DevExpress.Data.Linq.GetQueryableEventArgs e)
        {

            // Dispose of the DataContext
            ((Hesabdari_TG_N1_V1.Models.MyContext)e.Tag).Dispose();
        }

        private void btnRefresh_Click(object sender, EventArgs e)
        {
            FrmListAnbars_Load(null,null);
        }

        private void FrmListAnbars_Load(object sender, EventArgs e)
        {
            // This line of code is generated by Data Source Configuration Wizard
            this.entityInstantFeedbackSource1.GetQueryable += entityInstantFeedbackSource1_GetQueryable;
            // This line of code is generated by Data Source Configuration Wizard
            this.entityInstantFeedbackSource1.DismissQueryable += entityInstantFeedbackSource1_DismissQueryable;

        }
    }
}