/****************************** Ghost.github.io ******************************\
*	Module Name:	AnbarsName.cs
*	Project:		Hesabdari_TG_N1_V1
*	Copyright (C) 2018 Kamal Khayati, All rights reserved.
*	This software may be modified and distributed under the terms of the MIT license.  See LICENSE file for details.
*
*	Written by Kamal Khayati <Kamal1355@gmail.com>,  2018 / 12 / 17   02:11 ب.ظ
*	
***********************************************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraBars;
using DevExpress.Data.Linq;
using Hesabdari_TG_N1_V1.Models;
using DevExpress.XtraGrid.Views.Grid;

namespace Hesabdari_TG_N1_V1.Forms.Base.AnbarKala
{
    public partial class FrmListAnbars : DevExpress.XtraEditors.XtraForm
    {

        public FrmListAnbars()
        {
            InitializeComponent();
            FillGridViewWhitInstantFeedbackSource();
            //FillGridViewWhitServerModeSource();
        }
        public void FillGridViewWhitServerModeSource()
        {
            // This line of code is generated by Data Source Configuration Wizard
            entityServerModeSource1.QueryableSource = new Hesabdari_TG_N1_V1.Models.MyContext().BSAnbars;
            gridControl1.DataSource = entityServerModeSource1;
        }
        public void FillGridViewWhitInstantFeedbackSource()
        {
            gridControl1.DataSource = null;
            // This line of code is generated by Data Source Configuration Wizard
            this.entityInstantFeedbackSource1.GetQueryable += entityInstantFeedbackSource1_GetQueryable;
            // This line of code is generated by Data Source Configuration Wizard
            this.entityInstantFeedbackSource1.DismissQueryable += entityInstantFeedbackSource1_DismissQueryable;
            gridControl1.DataSource = entityInstantFeedbackSource1;
        }
        private void btnDisplyList_Click(object sender, EventArgs e)
        {
            FillGridViewWhitInstantFeedbackSource();
            //FillGridViewWhitServerModeSource();
        }

        private void FrmListAnbars_Load(object sender, EventArgs e)
        {
        }

        private void gridView1_CustomUnboundColumnData(object sender, DevExpress.XtraGrid.Views.Base.CustomColumnDataEventArgs e)
        {
            HelpClass.HelpClass1.SetNumberRowsColumnUnboundGirdView(sender, e);
        }

        private void btnEdit_Click(object sender, EventArgs e)
        {
        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
        }

        //This event is generated by Data Source Configuration Wizard
        void entityInstantFeedbackSource1_GetQueryable(object sender, GetQueryableEventArgs e)
        {
            // Instantiate a new DataContext
            Hesabdari_TG_N1_V1.Models.MyContext dataContext = new Hesabdari_TG_N1_V1.Models.MyContext();
            // Assign a queryable source to the EntityInstantFeedbackSource
            e.QueryableSource = dataContext.BSAnbars;
            // Assign the DataContext to the Tag property,
            // to dispose of it in the DismissQueryable event handler
            e.Tag = dataContext;
        }

        //This event is generated by Data Source Configuration Wizard
        void entityInstantFeedbackSource1_DismissQueryable(object sender, GetQueryableEventArgs e)
        {
            // Dispose of the DataContext
            ((Hesabdari_TG_N1_V1.Models.MyContext)e.Tag).Dispose();
        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            FrmSaveAnbars fm = new FrmSaveAnbars(this);
            fm.Text = "اضافه کردن انبار جدید";
            fm.btnSave.Text = "ذخیره";
            fm.ShowDialog(this);

        }

        private void FrmListAnbars_Activated(object sender, EventArgs e)
        {
            //FillGridViewWhitInstantFeedbackSource();
            //FillGridViewWhitServerModeSource();
        }
    }
}