/****************************** Ghost.github.io ******************************\
*	Module Name:	FrmAccesslevel2.cs
*	Project:		SystemManagement
*	Copyright (C) 2018 Kamal Khayati, All rights reserved.
*	This software may be modified and distributed under the terms of the MIT license.  See LICENSE file for details.
*
*	Written by Kamal Khayati <Kamal1355@gmail.com>,  2019 / 1 / 20   10:46 AM
*	
***********************************************************************************/
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using DBHesabdari_TG;
using DevExpress.XtraEditors.Popup;

namespace SystemManagement.UsersSystem
{
    public partial class FrmAccesslevel2 : DevExpress.XtraEditors.XtraForm
    {
        public FrmAccesslevel2()
        {
            InitializeComponent();
        }
        public void FillcmbUsersList()
        {
            using (var dbContext = new MyContext())
            {
                try
                {
                    if (lblUserId.Text == "1")
                    {
                        // This line of code is generated by Data Source Configuration Wizard
                        dbContext.MsUsers.Where(s => s.UserIsActive == true && s.MsUserId != 1).Load();
                        // Bind data to control when loading complete
                        msUserBindingSource.DataSource = dbContext.MsUsers.Local.ToBindingList();
                    }
                    else
                    {
                        int _UserId = Convert.ToInt32(lblUserId.Text);
                        // This line of code is generated by Data Source Configuration Wizard
                        dbContext.MsUsers.Where(s => s.UserIsActive == true && s.MsUserId == _UserId).Load();
                        // Bind data to control when loading complete
                        msUserBindingSource.DataSource = dbContext.MsUsers.Local.ToBindingList();
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
        public void FilltreeListDafaterMali()
        {
            using (var dbContext = new MyContext())
            {
                try
                {
                    if (dbContext.MsMajmoes.Any())
                    {
                        // Call the Load method to get the data for the given DbSet from the database.
                        dbContext.MsAccessLevelDafaterMalis.Where(s => s.IsActive == true).OrderBy(s => s.KeyId).Load();
                        // This line of code is generated by Data Source Configuration Wizard
                        msAccessLevelDafaterMalisBindingSource.DataSource = dbContext.MsAccessLevelDafaterMalis.Local.ToBindingList();
                    }
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }
        }
        private void FrmAccesslevel2_Load(object sender, EventArgs e)
        {
            FillcmbUsersList();
            FilltreeListDafaterMali();
            treeListDafaterMali.ExpandAll();
        }
        private void btnEdit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (cmbUsersList.EditValue == null)
            {
                XtraMessageBox.Show("لطفا نام کاربر مورد نظر را انتخاب کنید", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            else
            {
                using (var db = new MyContext())
                {
                    try
                    {
                        int _UserId = Convert.ToInt32(cmbUsersList.EditValue);
                        /////////////////////////// ویرایش سطح دسترسی کاربران به لیست دفاتر مالی /////////////////////////////
                        var q = db.RmsUserBmsAccessLevelDafaterMalis.Where(s => s.MsUserId == _UserId).ToList();
                        if (q.Count > 0)
                        {
                            db.RmsUserBmsAccessLevelDafaterMalis.RemoveRange(q);
                        }

                        foreach (var item in treeListDafaterMali.GetNodeList().Except(treeListDafaterMali.GetAllCheckedNodes()))
                        {
                            if (item.CheckState == CheckState.Unchecked)
                            {
                                RmsUserBmsAccessLevelDafaterMali obj1 = new RmsUserBmsAccessLevelDafaterMali();
                                obj1.MsUserId = _UserId;
                                obj1.UserName = cmbUsersList.Edit.GetDisplayText(cmbUsersList.EditValue);
                                obj1.MsAccessLevelDafaterMaliId = Convert.ToInt32(item.GetValue(colMsAccessLevelDafaterMaliId));
                                obj1.KeyId = Convert.ToInt32(item.GetValue(colKeyId));
                                obj1.MajmoeId = Convert.ToInt32(item.GetValue(colMajmoeId));
                                obj1.VahedId = Convert.ToInt32(item.GetValue(colVahedId));
                                obj1.ShobeId = Convert.ToInt32(item.GetValue(colShobeId));
                                obj1.DoreMaliId = Convert.ToInt32(item.GetValue(colDoreMaliId));
                                obj1.IsActive = Convert.ToBoolean(item.GetValue(colIsActive));

                                db.RmsUserBmsAccessLevelDafaterMalis.Add(obj1);
                            }
                        }
                        //////////////////////////////////////////////////////////////////////////////////////////////////
                        db.SaveChanges();
                        XtraMessageBox.Show("عملیات باموفقیت انجام شد", "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    }
                    catch (Exception ex)
                    {
                        XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                            "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                    }
                }

            }
        }

        private void cmbUsersList_EditValueChanged(object sender, EventArgs e)
        {
            using (var db = new MyContext())
            {
                try
                {
                    int _UserId = Convert.ToInt32(cmbUsersList.EditValue);
                    var q = db.RmsUserBmsAccessLevelDafaterMalis.Where(f => f.MsUserId == _UserId).ToList();
                    if (q.Count > 0)
                    {
                        treeListDafaterMali.CheckAll();
                        q.ForEach(item =>
                        {
                            var node1 = treeListDafaterMali.FindNodeByKeyID(item.KeyId);
                            if (node1 != null)
                                treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                        });
                    }
                    else
                        treeListDafaterMali.CheckAll();
                }
                catch (Exception ex)
                {
                    XtraMessageBox.Show("عملیات با خطا مواجه شد" + "\n" + ex.Message,
                        "پیغام", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
            }

        }

        private void chkOpenCloseListDafaterMali_CheckedChanged(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (chkOpenCloseListDafaterMali.Checked)
                treeListDafaterMali.CollapseAll();
            else
                treeListDafaterMali.ExpandAll();
        }

        private void chkNotAllSelectListDafaterMali_CheckedChanged(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (chkNotAllSelectListDafaterMali.Checked)
                treeListDafaterMali.UncheckAll();
            else
                treeListDafaterMali.CheckAll();
        }

        private void btnPrintPreview_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if (ListDafaterMali.IsControlLoaded)
            {
                treeListDafaterMali.ShowRibbonPrintPreview();
            }

        }
        private void treeListDafaterMali_NodeChanged(object sender, DevExpress.XtraTreeList.NodeChangedEventArgs e)
        {
        }

        private void treeListDafaterMali_FocusedNodeChanged(object sender, DevExpress.XtraTreeList.FocusedNodeChangedEventArgs e)
        {

        }

        private void treeListDafaterMali_AfterCheckNode(object sender, DevExpress.XtraTreeList.NodeEventArgs e)
        {
            int a = Convert.ToInt32(e.Node.GetValue(colKeyId));
            if (a > 0)
            {
                if (a.ToString().Length == 2)
                {
                    if (treeListDafaterMali.FindNodeByKeyID(a).CheckState == CheckState.Checked)
                    {
                        treeListDafaterMali.GetNodeList().ForEach(item =>
                        {
                            if (Convert.ToInt32(item[colKeyId]) > a)
                            {
                                if (a.ToString().Substring(0, 2) == item[colKeyId].ToString().Substring(0, 2))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                }
                            }
                        });
                    }
                    else
                    {
                        treeListDafaterMali.GetNodeList().ForEach(item =>
                        {
                            if (Convert.ToInt32(item[colKeyId]) > a)
                            {
                                if (a.ToString().Substring(0, 2) == item[colKeyId].ToString().Substring(0, 2))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                }
                            }
                        });
                    }
                }
                else if (a.ToString().Length == 4)
                {
                    if (treeListDafaterMali.FindNodeByKeyID(a).CheckState == CheckState.Checked)
                    {
                        treeListDafaterMali.GetNodeList().ForEach(item =>
                        {
                            if (Convert.ToInt32(item[colKeyId]) > a)
                            {
                                if (a.ToString().Substring(0, 4) == item[colKeyId].ToString().Substring(0, 4))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                }
                            }
                            else
                            {
                                if (item[colKeyId].ToString().Length == 2)
                                {
                                    if (a.ToString().Substring(0, 2) == item[colKeyId].ToString().Substring(0, 2))
                                    {
                                        var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                        treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                    }
                                }
                            }
                        });
                    }
                    else
                    {
                        treeListDafaterMali.GetNodeList().ForEach(item =>
                        {
                            if (Convert.ToInt32(item[colKeyId]) > a)
                            {
                                if (a.ToString().Substring(0, 4) == item[colKeyId].ToString().Substring(0, 4))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                }
                            }
                            else
                            {
                                if (item[colKeyId].ToString().Length == 2)
                                {
                                    if (a.ToString().Substring(0, 2) == item[colKeyId].ToString().Substring(0, 2))
                                    {
                                        var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                        treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                    }
                                }
                            }

                        });
                    }
                }
                else if (a.ToString().Length == 6)
                {
                    if (treeListDafaterMali.FindNodeByKeyID(a).CheckState == CheckState.Checked)
                    {
                        treeListDafaterMali.GetNodeList().ForEach(item =>
                        {
                            if (Convert.ToInt32(item[colKeyId]) > a)
                            {
                                if (a.ToString().Substring(0, 6) == item[colKeyId].ToString().Substring(0, 6))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                }
                            }
                            else
                            {
                                if (item[colKeyId].ToString().Length == 4)
                                {
                                    if (a.ToString().Substring(0, 4) == item[colKeyId].ToString().Substring(0, 4))
                                    {
                                        var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                        treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                    }
                                }
                                else if (item[colKeyId].ToString().Length == 2)
                                {
                                    if (a.ToString().Substring(0, 2) == item[colKeyId].ToString().Substring(0, 2))
                                    {
                                        var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                        treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                    }
                                }
                            }
                        });
                    }
                    else
                    {
                        treeListDafaterMali.GetNodeList().ForEach(item =>
                        {
                            if (Convert.ToInt32(item[colKeyId]) > a)
                            {
                                if (a.ToString().Substring(0, 6) == item[colKeyId].ToString().Substring(0, 6))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                }
                            }
                            else
                            {
                                if (item[colKeyId].ToString().Length == 4)
                                {
                                    if (a.ToString().Substring(0, 4) == item[colKeyId].ToString().Substring(0, 4))
                                    {
                                        var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                        treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                    }
                                }
                                else if (item[colKeyId].ToString().Length == 2)
                                {
                                    if (a.ToString().Substring(0, 2) == item[colKeyId].ToString().Substring(0, 2))
                                    {
                                        var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                        treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                    }
                                }
                            }
                        });
                    }
                }
                else
                {
                    if (treeListDafaterMali.FindNodeByKeyID(a).CheckState == CheckState.Checked)
                    {
                        treeListDafaterMali.GetNodeList().ForEach(item =>
                        {
                            if (item[colKeyId].ToString().Length == 6)
                            {
                                if (a.ToString().Substring(0, 6) == item[colKeyId].ToString().Substring(0, 6))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                }
                            }
                            else if (item[colKeyId].ToString().Length == 4)
                            {
                                if (a.ToString().Substring(0, 4) == item[colKeyId].ToString().Substring(0, 4))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                }
                            }
                            else if (item[colKeyId].ToString().Length == 2)
                            {
                                if (a.ToString().Substring(0, 2) == item[colKeyId].ToString().Substring(0, 2))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Checked, false);
                                }
                            }
                        });
                    }
                    else
                    {
                        treeListDafaterMali.GetNodeList().ForEach(item =>
                        {
                            if (item[colKeyId].ToString().Length == 6)
                            {
                                if (a.ToString().Substring(0, 6) == item[colKeyId].ToString().Substring(0, 6))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                }
                            }
                            else if (item[colKeyId].ToString().Length == 4)
                            {
                                if (a.ToString().Substring(0, 4) == item[colKeyId].ToString().Substring(0, 4))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                }
                            }
                            else if (item[colKeyId].ToString().Length == 2)
                            {
                                if (a.ToString().Substring(0, 2) == item[colKeyId].ToString().Substring(0, 2))
                                {
                                    var node1 = treeListDafaterMali.FindNodeByKeyID(item[colKeyId]);
                                    treeListDafaterMali.SetNodeCheckState(node1, CheckState.Unchecked, false);
                                }
                            }
                        });

                    }

                }
            }
        }
    }
}